//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 05:31:18 PM PST 
//


package com.kcdataservices.affiliate.flights;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Represents the FareBasisCode of the flight
 * 
 * <p>Java class for FareBasisCodeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FareBasisCodeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="adultCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="childCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="infantCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FareBasisCodeType", propOrder = {
    "adultCode",
    "childCode",
    "infantCode"
})
public class FareBasisCodeType {

    protected String adultCode;
    protected String childCode;
    protected String infantCode;

    /**
     * Gets the value of the adultCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdultCode() {
        return adultCode;
    }

    /**
     * Sets the value of the adultCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdultCode(String value) {
        this.adultCode = value;
    }

    /**
     * Gets the value of the childCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildCode() {
        return childCode;
    }

    /**
     * Sets the value of the childCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildCode(String value) {
        this.childCode = value;
    }

    /**
     * Gets the value of the infantCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInfantCode() {
        return infantCode;
    }

    /**
     * Sets the value of the infantCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInfantCode(String value) {
        this.infantCode = value;
    }

}
