//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 05:31:18 PM PST 
//


package com.kcdataservices.affiliate.flights;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import com.kcdataservices.affiliate.common.PriceType;


/**
 * Represents the price structure for Flights
 * 
 * <p>Java class for FlightPriceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FlightPriceType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://affiliate.kcdataservices.com/common}PriceType">
 *       &lt;attribute name="pkgRefCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlightPriceType")
public class FlightPriceType
    extends PriceType
{

    @XmlAttribute(name = "pkgRefCode")
    protected String pkgRefCode;

    /**
     * Gets the value of the pkgRefCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPkgRefCode() {
        return pkgRefCode;
    }

    /**
     * Sets the value of the pkgRefCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPkgRefCode(String value) {
        this.pkgRefCode = value;
    }

}
