//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 05:31:18 PM PST 
//


package com.kcdataservices.affiliate.flights;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.kcdataservices.affiliate.common.BooleanFlagType;
import com.kcdataservices.affiliate.common.CabinTypeType;


/**
 * Represent the complete details of a flight segment
 * 
 * <p>Java class for FlightSegmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FlightSegmentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="flightNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="departingFrom" type="{http://affiliate.kcdataservices.com/common}CityCodeType"/>
 *         &lt;element name="arrivingTo" type="{http://affiliate.kcdataservices.com/common}CityCodeType"/>
 *         &lt;element name="departureTime" type="{http://affiliate.kcdataservices.com/common}DateTimeType"/>
 *         &lt;element name="arrivalTime" type="{http://affiliate.kcdataservices.com/common}DateTimeType"/>
 *         &lt;element name="carrier" type="{http://affiliate.kcdataservices.com/flights}CarrierType"/>
 *         &lt;element name="codeShareCarrier" type="{http://affiliate.kcdataservices.com/flights}CarrierType" minOccurs="0"/>
 *         &lt;element name="classOfService">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="1"/>
 *               &lt;pattern value="[a-zA-z]"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="seatsAvailable" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
 *         &lt;element name="rotation" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="noOfStops" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
 *         &lt;element name="travelTime" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *         &lt;element name="mealsServed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="aircraftType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cabinType" type="{http://affiliate.kcdataservices.com/common}CabinTypeType" minOccurs="0"/>
 *         &lt;element name="overNight" type="{http://affiliate.kcdataservices.com/common}BooleanFlagType" minOccurs="0"/>
 *         &lt;element name="eTicket" type="{http://affiliate.kcdataservices.com/common}BooleanFlagType" minOccurs="0"/>
 *         &lt;element name="fareBasisCode" type="{http://affiliate.kcdataservices.com/flights}FareBasisCodeType" minOccurs="0"/>
 *         &lt;element name="recordLocator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlightSegmentType", propOrder = {
    "flightNumber",
    "departingFrom",
    "arrivingTo",
    "departureTime",
    "arrivalTime",
    "carrier",
    "codeShareCarrier",
    "classOfService",
    "seatsAvailable",
    "rotation",
    "noOfStops",
    "travelTime",
    "mealsServed",
    "aircraftType",
    "cabinType",
    "overNight",
    "eTicket",
    "fareBasisCode",
    "recordLocator"
})
public class FlightSegmentType {

    @XmlElement(required = true)
    protected String flightNumber;
    @XmlElement(required = true)
    protected String departingFrom;
    @XmlElement(required = true)
    protected String arrivingTo;
    @XmlElement(required = true)
    protected XMLGregorianCalendar departureTime;
    @XmlElement(required = true)
    protected XMLGregorianCalendar arrivalTime;
    @XmlElement(required = true)
    protected CarrierType carrier;
    protected CarrierType codeShareCarrier;
    @XmlElement(required = true)
    protected String classOfService;
    @XmlSchemaType(name = "unsignedByte")
    protected Short seatsAvailable;
    protected String rotation;
    @XmlSchemaType(name = "unsignedByte")
    protected Short noOfStops;
    @XmlElement(required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger travelTime;
    protected String mealsServed;
    protected String aircraftType;
    protected CabinTypeType cabinType;
    protected BooleanFlagType overNight;
    protected BooleanFlagType eTicket;
    protected FareBasisCodeType fareBasisCode;
    protected String recordLocator;

    /**
     * Gets the value of the flightNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlightNumber() {
        return flightNumber;
    }

    /**
     * Sets the value of the flightNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlightNumber(String value) {
        this.flightNumber = value;
    }

    /**
     * Gets the value of the departingFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartingFrom() {
        return departingFrom;
    }

    /**
     * Sets the value of the departingFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartingFrom(String value) {
        this.departingFrom = value;
    }

    /**
     * Gets the value of the arrivingTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrivingTo() {
        return arrivingTo;
    }

    /**
     * Sets the value of the arrivingTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrivingTo(String value) {
        this.arrivingTo = value;
    }

    /**
     * Gets the value of the departureTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDepartureTime() {
        return departureTime;
    }

    /**
     * Sets the value of the departureTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDepartureTime(XMLGregorianCalendar value) {
        this.departureTime = value;
    }

    /**
     * Gets the value of the arrivalTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getArrivalTime() {
        return arrivalTime;
    }

    /**
     * Sets the value of the arrivalTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setArrivalTime(XMLGregorianCalendar value) {
        this.arrivalTime = value;
    }

    /**
     * Gets the value of the carrier property.
     * 
     * @return
     *     possible object is
     *     {@link CarrierType }
     *     
     */
    public CarrierType getCarrier() {
        return carrier;
    }

    /**
     * Sets the value of the carrier property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarrierType }
     *     
     */
    public void setCarrier(CarrierType value) {
        this.carrier = value;
    }

    /**
     * Gets the value of the codeShareCarrier property.
     * 
     * @return
     *     possible object is
     *     {@link CarrierType }
     *     
     */
    public CarrierType getCodeShareCarrier() {
        return codeShareCarrier;
    }

    /**
     * Sets the value of the codeShareCarrier property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarrierType }
     *     
     */
    public void setCodeShareCarrier(CarrierType value) {
        this.codeShareCarrier = value;
    }

    /**
     * Gets the value of the classOfService property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassOfService() {
        return classOfService;
    }

    /**
     * Sets the value of the classOfService property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassOfService(String value) {
        this.classOfService = value;
    }

    /**
     * Gets the value of the seatsAvailable property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getSeatsAvailable() {
        return seatsAvailable;
    }

    /**
     * Sets the value of the seatsAvailable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setSeatsAvailable(Short value) {
        this.seatsAvailable = value;
    }

    /**
     * Gets the value of the rotation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRotation() {
        return rotation;
    }

    /**
     * Sets the value of the rotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRotation(String value) {
        this.rotation = value;
    }

    /**
     * Gets the value of the noOfStops property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getNoOfStops() {
        return noOfStops;
    }

    /**
     * Sets the value of the noOfStops property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setNoOfStops(Short value) {
        this.noOfStops = value;
    }

    /**
     * Gets the value of the travelTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTravelTime() {
        return travelTime;
    }

    /**
     * Sets the value of the travelTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTravelTime(BigInteger value) {
        this.travelTime = value;
    }

    /**
     * Gets the value of the mealsServed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMealsServed() {
        return mealsServed;
    }

    /**
     * Sets the value of the mealsServed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMealsServed(String value) {
        this.mealsServed = value;
    }

    /**
     * Gets the value of the aircraftType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAircraftType() {
        return aircraftType;
    }

    /**
     * Sets the value of the aircraftType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAircraftType(String value) {
        this.aircraftType = value;
    }

    /**
     * Gets the value of the cabinType property.
     * 
     * @return
     *     possible object is
     *     {@link CabinTypeType }
     *     
     */
    public CabinTypeType getCabinType() {
        return cabinType;
    }

    /**
     * Sets the value of the cabinType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CabinTypeType }
     *     
     */
    public void setCabinType(CabinTypeType value) {
        this.cabinType = value;
    }

    /**
     * Gets the value of the overNight property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanFlagType }
     *     
     */
    public BooleanFlagType getOverNight() {
        return overNight;
    }

    /**
     * Sets the value of the overNight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanFlagType }
     *     
     */
    public void setOverNight(BooleanFlagType value) {
        this.overNight = value;
    }

    /**
     * Gets the value of the eTicket property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanFlagType }
     *     
     */
    public BooleanFlagType getETicket() {
        return eTicket;
    }

    /**
     * Sets the value of the eTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanFlagType }
     *     
     */
    public void setETicket(BooleanFlagType value) {
        this.eTicket = value;
    }

    /**
     * Gets the value of the fareBasisCode property.
     * 
     * @return
     *     possible object is
     *     {@link FareBasisCodeType }
     *     
     */
    public FareBasisCodeType getFareBasisCode() {
        return fareBasisCode;
    }

    /**
     * Sets the value of the fareBasisCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link FareBasisCodeType }
     *     
     */
    public void setFareBasisCode(FareBasisCodeType value) {
        this.fareBasisCode = value;
    }

    /**
     * Gets the value of the recordLocator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordLocator() {
        return recordLocator;
    }

    /**
     * Sets the value of the recordLocator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordLocator(String value) {
        this.recordLocator = value;
    }

}
