//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 05:31:18 PM PST 
//


package com.kcdataservices.affiliate.flights;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.kcdataservices.affiliate.common.BooleanFlagType;


/**
 * Represents the complete details of a each direction Flight
 * 
 * <p>Java class for FlightType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FlightType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="departingFrom" type="{http://affiliate.kcdataservices.com/common}CityCodeType"/>
 *         &lt;element name="arrivingTo" type="{http://affiliate.kcdataservices.com/common}CityCodeType"/>
 *         &lt;element name="departureTime" type="{http://affiliate.kcdataservices.com/common}DateTimeType"/>
 *         &lt;element name="arrivalTime" type="{http://affiliate.kcdataservices.com/common}DateTimeType"/>
 *         &lt;element name="travelTime" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *         &lt;element name="overNight" type="{http://affiliate.kcdataservices.com/common}BooleanFlagType"/>
 *         &lt;element name="flightSegment" type="{http://affiliate.kcdataservices.com/flights}FlightSegmentType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlightType", propOrder = {
    "id",
    "departingFrom",
    "arrivingTo",
    "departureTime",
    "arrivalTime",
    "travelTime",
    "overNight",
    "flightSegment"
})
public class FlightType {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected String departingFrom;
    @XmlElement(required = true)
    protected String arrivingTo;
    @XmlElement(required = true)
    protected XMLGregorianCalendar departureTime;
    @XmlElement(required = true)
    protected XMLGregorianCalendar arrivalTime;
    @XmlElement(required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger travelTime;
    @XmlElement(required = true)
    protected BooleanFlagType overNight;
    @XmlElement(required = true)
    protected List<FlightSegmentType> flightSegment;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the departingFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartingFrom() {
        return departingFrom;
    }

    /**
     * Sets the value of the departingFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartingFrom(String value) {
        this.departingFrom = value;
    }

    /**
     * Gets the value of the arrivingTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrivingTo() {
        return arrivingTo;
    }

    /**
     * Sets the value of the arrivingTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrivingTo(String value) {
        this.arrivingTo = value;
    }

    /**
     * Gets the value of the departureTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDepartureTime() {
        return departureTime;
    }

    /**
     * Sets the value of the departureTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDepartureTime(XMLGregorianCalendar value) {
        this.departureTime = value;
    }

    /**
     * Gets the value of the arrivalTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getArrivalTime() {
        return arrivalTime;
    }

    /**
     * Sets the value of the arrivalTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setArrivalTime(XMLGregorianCalendar value) {
        this.arrivalTime = value;
    }

    /**
     * Gets the value of the travelTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTravelTime() {
        return travelTime;
    }

    /**
     * Sets the value of the travelTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTravelTime(BigInteger value) {
        this.travelTime = value;
    }

    /**
     * Gets the value of the overNight property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanFlagType }
     *     
     */
    public BooleanFlagType getOverNight() {
        return overNight;
    }

    /**
     * Sets the value of the overNight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanFlagType }
     *     
     */
    public void setOverNight(BooleanFlagType value) {
        this.overNight = value;
    }

    /**
     * Gets the value of the flightSegment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the flightSegment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFlightSegment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FlightSegmentType }
     * 
     * 
     */
    public List<FlightSegmentType> getFlightSegment() {
        if (flightSegment == null) {
            flightSegment = new ArrayList<FlightSegmentType>();
        }
        return this.flightSegment;
    }

}
