//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.20 at 04:31:23 PM PDT 
//


package com.kcdataservices.affiliate.flights;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://affiliate.kcdataservices.com/flights}flightType"/>
 *         &lt;element ref="{http://affiliate.kcdataservices.com/flights}outBoundFlight"/>
 *         &lt;element ref="{http://affiliate.kcdataservices.com/flights}inBoundFlight"/>
 *         &lt;element ref="{http://affiliate.kcdataservices.com/flights}carrier"/>
 *         &lt;element ref="{http://affiliate.kcdataservices.com/flights}price"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}byte">
 *             &lt;enumeration value="1"/>
 *             &lt;enumeration value="10"/>
 *             &lt;enumeration value="11"/>
 *             &lt;enumeration value="12"/>
 *             &lt;enumeration value="13"/>
 *             &lt;enumeration value="14"/>
 *             &lt;enumeration value="15"/>
 *             &lt;enumeration value="16"/>
 *             &lt;enumeration value="17"/>
 *             &lt;enumeration value="18"/>
 *             &lt;enumeration value="19"/>
 *             &lt;enumeration value="2"/>
 *             &lt;enumeration value="20"/>
 *             &lt;enumeration value="21"/>
 *             &lt;enumeration value="22"/>
 *             &lt;enumeration value="23"/>
 *             &lt;enumeration value="24"/>
 *             &lt;enumeration value="25"/>
 *             &lt;enumeration value="26"/>
 *             &lt;enumeration value="27"/>
 *             &lt;enumeration value="28"/>
 *             &lt;enumeration value="29"/>
 *             &lt;enumeration value="3"/>
 *             &lt;enumeration value="30"/>
 *             &lt;enumeration value="31"/>
 *             &lt;enumeration value="32"/>
 *             &lt;enumeration value="33"/>
 *             &lt;enumeration value="34"/>
 *             &lt;enumeration value="35"/>
 *             &lt;enumeration value="36"/>
 *             &lt;enumeration value="37"/>
 *             &lt;enumeration value="38"/>
 *             &lt;enumeration value="39"/>
 *             &lt;enumeration value="4"/>
 *             &lt;enumeration value="40"/>
 *             &lt;enumeration value="41"/>
 *             &lt;enumeration value="42"/>
 *             &lt;enumeration value="43"/>
 *             &lt;enumeration value="44"/>
 *             &lt;enumeration value="45"/>
 *             &lt;enumeration value="46"/>
 *             &lt;enumeration value="47"/>
 *             &lt;enumeration value="48"/>
 *             &lt;enumeration value="49"/>
 *             &lt;enumeration value="5"/>
 *             &lt;enumeration value="50"/>
 *             &lt;enumeration value="51"/>
 *             &lt;enumeration value="52"/>
 *             &lt;enumeration value="53"/>
 *             &lt;enumeration value="54"/>
 *             &lt;enumeration value="55"/>
 *             &lt;enumeration value="56"/>
 *             &lt;enumeration value="57"/>
 *             &lt;enumeration value="58"/>
 *             &lt;enumeration value="59"/>
 *             &lt;enumeration value="6"/>
 *             &lt;enumeration value="60"/>
 *             &lt;enumeration value="61"/>
 *             &lt;enumeration value="62"/>
 *             &lt;enumeration value="63"/>
 *             &lt;enumeration value="64"/>
 *             &lt;enumeration value="65"/>
 *             &lt;enumeration value="66"/>
 *             &lt;enumeration value="67"/>
 *             &lt;enumeration value="68"/>
 *             &lt;enumeration value="69"/>
 *             &lt;enumeration value="7"/>
 *             &lt;enumeration value="70"/>
 *             &lt;enumeration value="71"/>
 *             &lt;enumeration value="72"/>
 *             &lt;enumeration value="73"/>
 *             &lt;enumeration value="74"/>
 *             &lt;enumeration value="75"/>
 *             &lt;enumeration value="76"/>
 *             &lt;enumeration value="77"/>
 *             &lt;enumeration value="78"/>
 *             &lt;enumeration value="79"/>
 *             &lt;enumeration value="8"/>
 *             &lt;enumeration value="80"/>
 *             &lt;enumeration value="81"/>
 *             &lt;enumeration value="82"/>
 *             &lt;enumeration value="83"/>
 *             &lt;enumeration value="84"/>
 *             &lt;enumeration value="85"/>
 *             &lt;enumeration value="86"/>
 *             &lt;enumeration value="87"/>
 *             &lt;enumeration value="88"/>
 *             &lt;enumeration value="89"/>
 *             &lt;enumeration value="9"/>
 *             &lt;enumeration value="90"/>
 *             &lt;enumeration value="91"/>
 *             &lt;enumeration value="92"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "flightType",
    "outBoundFlight",
    "inBoundFlight",
    "carrier",
    "price"
})
@XmlRootElement(name = "flightOption")
public class FlightOption {

    @XmlElement(required = true)
    protected String flightType;
    @XmlElement(required = true)
    protected OutBoundFlight outBoundFlight;
    @XmlElement(required = true)
    protected InBoundFlight inBoundFlight;
    @XmlElement(required = true)
    protected Carrier carrier;
    @XmlElement(required = true)
    protected Price price;
    @XmlAttribute(required = true)
    protected byte id;

    /**
     * Gets the value of the flightType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlightType() {
        return flightType;
    }

    /**
     * Sets the value of the flightType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlightType(String value) {
        this.flightType = value;
    }

    /**
     * Gets the value of the outBoundFlight property.
     * 
     * @return
     *     possible object is
     *     {@link OutBoundFlight }
     *     
     */
    public OutBoundFlight getOutBoundFlight() {
        return outBoundFlight;
    }

    /**
     * Sets the value of the outBoundFlight property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutBoundFlight }
     *     
     */
    public void setOutBoundFlight(OutBoundFlight value) {
        this.outBoundFlight = value;
    }

    /**
     * Gets the value of the inBoundFlight property.
     * 
     * @return
     *     possible object is
     *     {@link InBoundFlight }
     *     
     */
    public InBoundFlight getInBoundFlight() {
        return inBoundFlight;
    }

    /**
     * Sets the value of the inBoundFlight property.
     * 
     * @param value
     *     allowed object is
     *     {@link InBoundFlight }
     *     
     */
    public void setInBoundFlight(InBoundFlight value) {
        this.inBoundFlight = value;
    }

    /**
     * Gets the value of the carrier property.
     * 
     * @return
     *     possible object is
     *     {@link Carrier }
     *     
     */
    public Carrier getCarrier() {
        return carrier;
    }

    /**
     * Sets the value of the carrier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Carrier }
     *     
     */
    public void setCarrier(Carrier value) {
        this.carrier = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link Price }
     *     
     */
    public Price getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link Price }
     *     
     */
    public void setPrice(Price value) {
        this.price = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public byte getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(byte value) {
        this.id = value;
    }

}
