//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.20 at 04:31:23 PM PDT 
//


package com.kcdataservices.affiliate.flights;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://affiliate.kcdataservices.com/flights}id"/>
 *         &lt;element ref="{http://affiliate.kcdataservices.com/flights}departingFrom"/>
 *         &lt;element ref="{http://affiliate.kcdataservices.com/flights}arrivingTo"/>
 *         &lt;element ref="{http://affiliate.kcdataservices.com/flights}departureTime"/>
 *         &lt;element ref="{http://affiliate.kcdataservices.com/flights}arrivalTime"/>
 *         &lt;element ref="{http://affiliate.kcdataservices.com/flights}travelTime"/>
 *         &lt;element ref="{http://affiliate.kcdataservices.com/flights}overNight"/>
 *         &lt;element ref="{http://affiliate.kcdataservices.com/flights}flightSegment" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "departingFrom",
    "arrivingTo",
    "departureTime",
    "arrivalTime",
    "travelTime",
    "overNight",
    "flightSegment"
})
@XmlRootElement(name = "outBoundFlight")
public class OutBoundFlight {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected String departingFrom;
    @XmlElement(required = true)
    protected String arrivingTo;
    @XmlElement(required = true)
    protected XMLGregorianCalendar departureTime;
    @XmlElement(required = true)
    protected XMLGregorianCalendar arrivalTime;
    protected int travelTime;
    @XmlElement(required = true)
    protected String overNight;
    @XmlElement(required = true)
    protected List<FlightSegment> flightSegment;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the departingFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartingFrom() {
        return departingFrom;
    }

    /**
     * Sets the value of the departingFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartingFrom(String value) {
        this.departingFrom = value;
    }

    /**
     * Gets the value of the arrivingTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrivingTo() {
        return arrivingTo;
    }

    /**
     * Sets the value of the arrivingTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrivingTo(String value) {
        this.arrivingTo = value;
    }

    /**
     * Gets the value of the departureTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDepartureTime() {
        return departureTime;
    }

    /**
     * Sets the value of the departureTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDepartureTime(XMLGregorianCalendar value) {
        this.departureTime = value;
    }

    /**
     * Gets the value of the arrivalTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getArrivalTime() {
        return arrivalTime;
    }

    /**
     * Sets the value of the arrivalTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setArrivalTime(XMLGregorianCalendar value) {
        this.arrivalTime = value;
    }

    /**
     * Gets the value of the travelTime property.
     * 
     */
    public int getTravelTime() {
        return travelTime;
    }

    /**
     * Sets the value of the travelTime property.
     * 
     */
    public void setTravelTime(int value) {
        this.travelTime = value;
    }

    /**
     * Gets the value of the overNight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOverNight() {
        return overNight;
    }

    /**
     * Sets the value of the overNight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOverNight(String value) {
        this.overNight = value;
    }

    /**
     * Gets the value of the flightSegment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the flightSegment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFlightSegment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FlightSegment }
     * 
     * 
     */
    public List<FlightSegment> getFlightSegment() {
        if (flightSegment == null) {
            flightSegment = new ArrayList<FlightSegment>();
        }
        return this.flightSegment;
    }

}
