//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.20 at 04:31:23 PM PDT 
//


package com.kcdataservices.affiliate.flights;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://affiliate.kcdataservices.com/flights}fullOccupancyPrice"/>
 *         &lt;element ref="{http://affiliate.kcdataservices.com/flights}perPersonPrice"/>
 *         &lt;element ref="{http://affiliate.kcdataservices.com/flights}promoSavings"/>
 *       &lt;/sequence>
 *       &lt;attribute name="pkgRefCode" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="0S"/>
 *             &lt;enumeration value="1B"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fullOccupancyPrice",
    "perPersonPrice",
    "promoSavings"
})
@XmlRootElement(name = "price")
public class Price {

    @XmlElement(required = true)
    protected BigDecimal fullOccupancyPrice;
    @XmlElement(required = true)
    protected BigDecimal perPersonPrice;
    @XmlElement(required = true)
    protected BigDecimal promoSavings;
    @XmlAttribute(required = true)
    protected String pkgRefCode;

    /**
     * Gets the value of the fullOccupancyPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFullOccupancyPrice() {
        return fullOccupancyPrice;
    }

    /**
     * Sets the value of the fullOccupancyPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFullOccupancyPrice(BigDecimal value) {
        this.fullOccupancyPrice = value;
    }

    /**
     * Gets the value of the perPersonPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPerPersonPrice() {
        return perPersonPrice;
    }

    /**
     * Sets the value of the perPersonPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPerPersonPrice(BigDecimal value) {
        this.perPersonPrice = value;
    }

    /**
     * Gets the value of the promoSavings property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPromoSavings() {
        return promoSavings;
    }

    /**
     * Sets the value of the promoSavings property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPromoSavings(BigDecimal value) {
        this.promoSavings = value;
    }

    /**
     * Gets the value of the pkgRefCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPkgRefCode() {
        return pkgRefCode;
    }

    /**
     * Sets the value of the pkgRefCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPkgRefCode(String value) {
        this.pkgRefCode = value;
    }

}
