//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 04:20:56 PM PST 
//


package com.kcdataservices.affiliate.packages;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import com.kcdataservices.affiliate.common.PriceType;
import com.kcdataservices.affiliate.flights.SelectedFlightType;
import com.kcdataservices.affiliate.hotels.SelectedHotelType;
import com.kcdataservices.affiliate.vehicles.SelectedVehicleType;


/**
 * Represents the details of multi-destination package.  Although minOccurs for selectedFlights, selectedHotels, selectedVehicles is 0, either of three components is expected.  This validation is handled in service.
 * 
 * <p>Java class for SelectedMultiDestinationPackageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SelectedMultiDestinationPackageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="selectedFlights" type="{http://affiliate.kcdataservices.com/flights}SelectedFlightType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="selectedHotels" type="{http://affiliate.kcdataservices.com/hotels}SelectedHotelType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="selectedVehicles" type="{http://affiliate.kcdataservices.com/vehicles}SelectedVehicleType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="price" type="{http://affiliate.kcdataservices.com/common}PriceType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SelectedMultiDestinationPackageType", propOrder = {
    "selectedFlights",
    "selectedHotels",
    "selectedVehicles",
    "price"
})
public class SelectedMultiDestinationPackageType {

    protected List<SelectedFlightType> selectedFlights;
    protected List<SelectedHotelType> selectedHotels;
    protected List<SelectedVehicleType> selectedVehicles;
    @XmlElement(required = true)
    protected PriceType price;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "anySimpleType")
    protected String id;

    /**
     * Gets the value of the selectedFlights property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the selectedFlights property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSelectedFlights().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SelectedFlightType }
     * 
     * 
     */
    public List<SelectedFlightType> getSelectedFlights() {
        if (selectedFlights == null) {
            selectedFlights = new ArrayList<SelectedFlightType>();
        }
        return this.selectedFlights;
    }

    /**
     * Gets the value of the selectedHotels property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the selectedHotels property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSelectedHotels().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SelectedHotelType }
     * 
     * 
     */
    public List<SelectedHotelType> getSelectedHotels() {
        if (selectedHotels == null) {
            selectedHotels = new ArrayList<SelectedHotelType>();
        }
        return this.selectedHotels;
    }

    /**
     * Gets the value of the selectedVehicles property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the selectedVehicles property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSelectedVehicles().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SelectedVehicleType }
     * 
     * 
     */
    public List<SelectedVehicleType> getSelectedVehicles() {
        if (selectedVehicles == null) {
            selectedVehicles = new ArrayList<SelectedVehicleType>();
        }
        return this.selectedVehicles;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link PriceType }
     *     
     */
    public PriceType getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceType }
     *     
     */
    public void setPrice(PriceType value) {
        this.price = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
