//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 04:20:56 PM PST 
//


package com.kcdataservices.affiliate.packages;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import com.kcdataservices.affiliate.common.PriceType;
import com.kcdataservices.affiliate.flights.SelectedFlightType;
import com.kcdataservices.affiliate.hotels.SelectedHotelType;
import com.kcdataservices.affiliate.vehicles.SelectedVehicleType;


/**
 * Represents the details of the selected package
 * 
 * <p>Java class for SelectedPackageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SelectedPackageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="selectedFlight" type="{http://affiliate.kcdataservices.com/flights}SelectedFlightType" minOccurs="0"/>
 *         &lt;element name="selectedHotel" type="{http://affiliate.kcdataservices.com/hotels}SelectedHotelType" minOccurs="0"/>
 *         &lt;element name="selectedVehicle" type="{http://affiliate.kcdataservices.com/vehicles}SelectedVehicleType" minOccurs="0"/>
 *         &lt;element name="price" type="{http://affiliate.kcdataservices.com/common}PriceType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SelectedPackageType", propOrder = {
    "selectedFlight",
    "selectedHotel",
    "selectedVehicle",
    "price"
})
public class SelectedPackageType {

    protected SelectedFlightType selectedFlight;
    protected SelectedHotelType selectedHotel;
    protected SelectedVehicleType selectedVehicle;
    protected PriceType price;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "anySimpleType")
    protected String id;

    /**
     * Gets the value of the selectedFlight property.
     * 
     * @return
     *     possible object is
     *     {@link SelectedFlightType }
     *     
     */
    public SelectedFlightType getSelectedFlight() {
        return selectedFlight;
    }

    /**
     * Sets the value of the selectedFlight property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelectedFlightType }
     *     
     */
    public void setSelectedFlight(SelectedFlightType value) {
        this.selectedFlight = value;
    }

    /**
     * Gets the value of the selectedHotel property.
     * 
     * @return
     *     possible object is
     *     {@link SelectedHotelType }
     *     
     */
    public SelectedHotelType getSelectedHotel() {
        return selectedHotel;
    }

    /**
     * Sets the value of the selectedHotel property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelectedHotelType }
     *     
     */
    public void setSelectedHotel(SelectedHotelType value) {
        this.selectedHotel = value;
    }

    /**
     * Gets the value of the selectedVehicle property.
     * 
     * @return
     *     possible object is
     *     {@link SelectedVehicleType }
     *     
     */
    public SelectedVehicleType getSelectedVehicle() {
        return selectedVehicle;
    }

    /**
     * Sets the value of the selectedVehicle property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelectedVehicleType }
     *     
     */
    public void setSelectedVehicle(SelectedVehicleType value) {
        this.selectedVehicle = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link PriceType }
     *     
     */
    public PriceType getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceType }
     *     
     */
    public void setPrice(PriceType value) {
        this.price = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
