//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 04:20:56 PM PST 
//


package com.kcdataservices.affiliate.insurance;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.kcdataservices.affiliate.common.BooleanFlagType;


/**
 * Represent the Insurance Deatils
 * 
 * <p>Java class for InsuranceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InsuranceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="detailedDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="validFrom" type="{http://affiliate.kcdataservices.com/common}DateType"/>
 *         &lt;element name="validTo" type="{http://affiliate.kcdataservices.com/common}DateType" minOccurs="0"/>
 *         &lt;element name="vacationType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="C"/>
 *               &lt;enumeration value="S"/>
 *               &lt;enumeration value="L"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="vacationTypeDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="adultPrice" type="{http://affiliate.kcdataservices.com/common}AmountType"/>
 *         &lt;element name="childPrice" type="{http://affiliate.kcdataservices.com/common}AmountType" minOccurs="0"/>
 *         &lt;element name="childRuleDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="childMinAge" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
 *         &lt;element name="childMaxAge" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
 *         &lt;element name="optionalIns" type="{http://affiliate.kcdataservices.com/common}BooleanFlagType" minOccurs="0"/>
 *         &lt;element name="maxQuantity" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InsuranceType", propOrder = {
    "code",
    "name",
    "detailedDescription",
    "validFrom",
    "validTo",
    "vacationType",
    "vacationTypeDescription",
    "adultPrice",
    "childPrice",
    "childRuleDesc",
    "childMinAge",
    "childMaxAge",
    "optionalIns",
    "maxQuantity"
})
@XmlSeeAlso({
    SelectedInsuranceType.class
})
public class InsuranceType {

    @XmlElement(required = true)
    protected String code;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String detailedDescription;
    @XmlElement(required = true)
    protected XMLGregorianCalendar validFrom;
    protected XMLGregorianCalendar validTo;
    @XmlElement(required = true)
    protected String vacationType;
    @XmlElement(required = true)
    protected String vacationTypeDescription;
    protected double adultPrice;
    protected Double childPrice;
    protected String childRuleDesc;
    protected Byte childMinAge;
    protected Byte childMaxAge;
    protected BooleanFlagType optionalIns;
    protected Byte maxQuantity;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "anySimpleType")
    protected String id;

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the detailedDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDetailedDescription() {
        return detailedDescription;
    }

    /**
     * Sets the value of the detailedDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDetailedDescription(String value) {
        this.detailedDescription = value;
    }

    /**
     * Gets the value of the validFrom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidFrom() {
        return validFrom;
    }

    /**
     * Sets the value of the validFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidFrom(XMLGregorianCalendar value) {
        this.validFrom = value;
    }

    /**
     * Gets the value of the validTo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidTo() {
        return validTo;
    }

    /**
     * Sets the value of the validTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidTo(XMLGregorianCalendar value) {
        this.validTo = value;
    }

    /**
     * Gets the value of the vacationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVacationType() {
        return vacationType;
    }

    /**
     * Sets the value of the vacationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVacationType(String value) {
        this.vacationType = value;
    }

    /**
     * Gets the value of the vacationTypeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVacationTypeDescription() {
        return vacationTypeDescription;
    }

    /**
     * Sets the value of the vacationTypeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVacationTypeDescription(String value) {
        this.vacationTypeDescription = value;
    }

    /**
     * Gets the value of the adultPrice property.
     * 
     */
    public double getAdultPrice() {
        return adultPrice;
    }

    /**
     * Sets the value of the adultPrice property.
     * 
     */
    public void setAdultPrice(double value) {
        this.adultPrice = value;
    }

    /**
     * Gets the value of the childPrice property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getChildPrice() {
        return childPrice;
    }

    /**
     * Sets the value of the childPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setChildPrice(Double value) {
        this.childPrice = value;
    }

    /**
     * Gets the value of the childRuleDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildRuleDesc() {
        return childRuleDesc;
    }

    /**
     * Sets the value of the childRuleDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildRuleDesc(String value) {
        this.childRuleDesc = value;
    }

    /**
     * Gets the value of the childMinAge property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getChildMinAge() {
        return childMinAge;
    }

    /**
     * Sets the value of the childMinAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setChildMinAge(Byte value) {
        this.childMinAge = value;
    }

    /**
     * Gets the value of the childMaxAge property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getChildMaxAge() {
        return childMaxAge;
    }

    /**
     * Sets the value of the childMaxAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setChildMaxAge(Byte value) {
        this.childMaxAge = value;
    }

    /**
     * Gets the value of the optionalIns property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanFlagType }
     *     
     */
    public BooleanFlagType getOptionalIns() {
        return optionalIns;
    }

    /**
     * Sets the value of the optionalIns property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanFlagType }
     *     
     */
    public void setOptionalIns(BooleanFlagType value) {
        this.optionalIns = value;
    }

    /**
     * Gets the value of the maxQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getMaxQuantity() {
        return maxQuantity;
    }

    /**
     * Sets the value of the maxQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setMaxQuantity(Byte value) {
        this.maxQuantity = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
