//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 04:20:56 PM PST 
//


package com.kcdataservices.affiliate.insurance;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Represents the selected insurance details
 * 
 * <p>Java class for SelectedInsuranceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SelectedInsuranceType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://affiliate.kcdataservices.com/insurance}InsuranceType">
 *       &lt;sequence>
 *         &lt;element name="adultsQty" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="childQty" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
 *         &lt;element name="infantQty" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
 *         &lt;element name="lapChildQty" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
 *         &lt;element name="totalPrice" type="{http://affiliate.kcdataservices.com/common}AmountType" minOccurs="0"/>
 *         &lt;element name="guestAllocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SelectedInsuranceType", propOrder = {
    "adultsQty",
    "childQty",
    "infantQty",
    "lapChildQty",
    "totalPrice",
    "guestAllocation"
})
public class SelectedInsuranceType
    extends InsuranceType
{

    protected byte adultsQty;
    protected Byte childQty;
    protected Byte infantQty;
    protected Byte lapChildQty;
    protected Double totalPrice;
    protected String guestAllocation;

    /**
     * Gets the value of the adultsQty property.
     * 
     */
    public byte getAdultsQty() {
        return adultsQty;
    }

    /**
     * Sets the value of the adultsQty property.
     * 
     */
    public void setAdultsQty(byte value) {
        this.adultsQty = value;
    }

    /**
     * Gets the value of the childQty property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getChildQty() {
        return childQty;
    }

    /**
     * Sets the value of the childQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setChildQty(Byte value) {
        this.childQty = value;
    }

    /**
     * Gets the value of the infantQty property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getInfantQty() {
        return infantQty;
    }

    /**
     * Sets the value of the infantQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setInfantQty(Byte value) {
        this.infantQty = value;
    }

    /**
     * Gets the value of the lapChildQty property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getLapChildQty() {
        return lapChildQty;
    }

    /**
     * Sets the value of the lapChildQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setLapChildQty(Byte value) {
        this.lapChildQty = value;
    }

    /**
     * Gets the value of the totalPrice property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTotalPrice() {
        return totalPrice;
    }

    /**
     * Sets the value of the totalPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTotalPrice(Double value) {
        this.totalPrice = value;
    }

    /**
     * Gets the value of the guestAllocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuestAllocation() {
        return guestAllocation;
    }

    /**
     * Sets the value of the guestAllocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuestAllocation(String value) {
        this.guestAllocation = value;
    }

}
