//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 05:31:24 PM PST 
//


package com.kcdataservices.affiliate.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * All the options requested at specific destination
 * 
 * <p>Java class for DestinationOptionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DestinationOptionsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="destination" type="{http://affiliate.kcdataservices.com/common}CityCodeType"/>
 *         &lt;element name="noOfNights" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *         &lt;element name="airRequested" type="{http://affiliate.kcdataservices.com/common}BooleanFlagType"/>
 *         &lt;element name="hotelRequested" type="{http://affiliate.kcdataservices.com/common}BooleanFlagType"/>
 *         &lt;element name="vehicleRequested" type="{http://affiliate.kcdataservices.com/common}BooleanFlagType"/>
 *         &lt;element name="airOptions" type="{http://affiliate.kcdataservices.com/common}AirRequestOptionsType" minOccurs="0"/>
 *         &lt;element name="hotelOptions" type="{http://affiliate.kcdataservices.com/common}HotelRequestOptionsType" minOccurs="0"/>
 *         &lt;element name="vehicleOptions" type="{http://affiliate.kcdataservices.com/common}VehicleRequestOptionsType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DestinationOptionsType", propOrder = {
    "destination",
    "noOfNights",
    "airRequested",
    "hotelRequested",
    "vehicleRequested",
    "airOptions",
    "hotelOptions",
    "vehicleOptions"
})
public class DestinationOptionsType {

    @XmlElement(required = true)
    protected String destination;
    @XmlSchemaType(name = "unsignedByte")
    protected short noOfNights;
    @XmlElement(required = true, defaultValue = "N")
    protected BooleanFlagType airRequested;
    @XmlElement(required = true, defaultValue = "N")
    protected BooleanFlagType hotelRequested;
    @XmlElement(required = true, defaultValue = "N")
    protected BooleanFlagType vehicleRequested;
    protected AirRequestOptionsType airOptions;
    protected HotelRequestOptionsType hotelOptions;
    protected VehicleRequestOptionsType vehicleOptions;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "unsignedByte")
    protected Short id;

    /**
     * Gets the value of the destination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestination(String value) {
        this.destination = value;
    }

    /**
     * Gets the value of the noOfNights property.
     * 
     */
    public short getNoOfNights() {
        return noOfNights;
    }

    /**
     * Sets the value of the noOfNights property.
     * 
     */
    public void setNoOfNights(short value) {
        this.noOfNights = value;
    }

    /**
     * Gets the value of the airRequested property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanFlagType }
     *     
     */
    public BooleanFlagType getAirRequested() {
        return airRequested;
    }

    /**
     * Sets the value of the airRequested property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanFlagType }
     *     
     */
    public void setAirRequested(BooleanFlagType value) {
        this.airRequested = value;
    }

    /**
     * Gets the value of the hotelRequested property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanFlagType }
     *     
     */
    public BooleanFlagType getHotelRequested() {
        return hotelRequested;
    }

    /**
     * Sets the value of the hotelRequested property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanFlagType }
     *     
     */
    public void setHotelRequested(BooleanFlagType value) {
        this.hotelRequested = value;
    }

    /**
     * Gets the value of the vehicleRequested property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanFlagType }
     *     
     */
    public BooleanFlagType getVehicleRequested() {
        return vehicleRequested;
    }

    /**
     * Sets the value of the vehicleRequested property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanFlagType }
     *     
     */
    public void setVehicleRequested(BooleanFlagType value) {
        this.vehicleRequested = value;
    }

    /**
     * Gets the value of the airOptions property.
     * 
     * @return
     *     possible object is
     *     {@link AirRequestOptionsType }
     *     
     */
    public AirRequestOptionsType getAirOptions() {
        return airOptions;
    }

    /**
     * Sets the value of the airOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link AirRequestOptionsType }
     *     
     */
    public void setAirOptions(AirRequestOptionsType value) {
        this.airOptions = value;
    }

    /**
     * Gets the value of the hotelOptions property.
     * 
     * @return
     *     possible object is
     *     {@link HotelRequestOptionsType }
     *     
     */
    public HotelRequestOptionsType getHotelOptions() {
        return hotelOptions;
    }

    /**
     * Sets the value of the hotelOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link HotelRequestOptionsType }
     *     
     */
    public void setHotelOptions(HotelRequestOptionsType value) {
        this.hotelOptions = value;
    }

    /**
     * Gets the value of the vehicleOptions property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleRequestOptionsType }
     *     
     */
    public VehicleRequestOptionsType getVehicleOptions() {
        return vehicleOptions;
    }

    /**
     * Sets the value of the vehicleOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleRequestOptionsType }
     *     
     */
    public void setVehicleOptions(VehicleRequestOptionsType value) {
        this.vehicleOptions = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setId(Short value) {
        this.id = value;
    }

}
