//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 05:31:24 PM PST 
//


package com.kcdataservices.affiliate.common;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Indiacates the flight preferences
 * 
 * <p>Java class for FlightPreferencesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FlightPreferencesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="departureTimeOfTheDay" type="{http://affiliate.kcdataservices.com/common}TimeOfTheDayType" minOccurs="0"/>
 *         &lt;element name="arrivalTimeOfTheDay" type="{http://affiliate.kcdataservices.com/common}TimeOfTheDayType" minOccurs="0"/>
 *         &lt;element name="connectionCities" type="{http://affiliate.kcdataservices.com/common}CityCodeType" maxOccurs="2" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlightPreferencesType", propOrder = {
    "departureTimeOfTheDay",
    "arrivalTimeOfTheDay",
    "connectionCities"
})
public class FlightPreferencesType {

    protected TimeOfTheDayType departureTimeOfTheDay;
    protected TimeOfTheDayType arrivalTimeOfTheDay;
    protected List<String> connectionCities;

    /**
     * Gets the value of the departureTimeOfTheDay property.
     * 
     * @return
     *     possible object is
     *     {@link TimeOfTheDayType }
     *     
     */
    public TimeOfTheDayType getDepartureTimeOfTheDay() {
        return departureTimeOfTheDay;
    }

    /**
     * Sets the value of the departureTimeOfTheDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeOfTheDayType }
     *     
     */
    public void setDepartureTimeOfTheDay(TimeOfTheDayType value) {
        this.departureTimeOfTheDay = value;
    }

    /**
     * Gets the value of the arrivalTimeOfTheDay property.
     * 
     * @return
     *     possible object is
     *     {@link TimeOfTheDayType }
     *     
     */
    public TimeOfTheDayType getArrivalTimeOfTheDay() {
        return arrivalTimeOfTheDay;
    }

    /**
     * Sets the value of the arrivalTimeOfTheDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeOfTheDayType }
     *     
     */
    public void setArrivalTimeOfTheDay(TimeOfTheDayType value) {
        this.arrivalTimeOfTheDay = value;
    }

    /**
     * Gets the value of the connectionCities property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the connectionCities property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConnectionCities().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getConnectionCities() {
        if (connectionCities == null) {
            connectionCities = new ArrayList<String>();
        }
        return this.connectionCities;
    }

}
