//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 05:31:24 PM PST 
//


package com.kcdataservices.affiliate.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MealPlanType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MealPlanType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ALLI"/>
 *     &lt;enumeration value="INC"/>
 *     &lt;enumeration value="EP"/>
 *     &lt;enumeration value="BP"/>
 *     &lt;enumeration value="FAP"/>
 *     &lt;enumeration value="MAP"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MealPlanType")
@XmlEnum
public enum MealPlanType {

    ALLI,
    INC,
    EP,
    BP,
    FAP,
    MAP;

    public String value() {
        return name();
    }

    public static MealPlanType fromValue(String v) {
        return valueOf(v);
    }

}
