//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 05:31:24 PM PST 
//


package com.kcdataservices.affiliate.common;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.kcdataservices.affiliate.common package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.kcdataservices.affiliate.common
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ApplicationInfoType }
     * 
     */
    public ApplicationInfoType createApplicationInfoType() {
        return new ApplicationInfoType();
    }

    /**
     * Create an instance of {@link SearchCriteriaType }
     * 
     */
    public SearchCriteriaType createSearchCriteriaType() {
        return new SearchCriteriaType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link PaymentInformationType }
     * 
     */
    public PaymentInformationType createPaymentInformationType() {
        return new PaymentInformationType();
    }

    /**
     * Create an instance of {@link PromotionType }
     * 
     */
    public PromotionType createPromotionType() {
        return new PromotionType();
    }

    /**
     * Create an instance of {@link PaxTypePriceBreakupType }
     * 
     */
    public PaxTypePriceBreakupType createPaxTypePriceBreakupType() {
        return new PaxTypePriceBreakupType();
    }

    /**
     * Create an instance of {@link OccupancyType }
     * 
     */
    public OccupancyType createOccupancyType() {
        return new OccupancyType();
    }

    /**
     * Create an instance of {@link PassengerType }
     * 
     */
    public PassengerType createPassengerType() {
        return new PassengerType();
    }

    /**
     * Create an instance of {@link AirRequestOptionsType }
     * 
     */
    public AirRequestOptionsType createAirRequestOptionsType() {
        return new AirRequestOptionsType();
    }

    /**
     * Create an instance of {@link VehicleRequestOptionsType }
     * 
     */
    public VehicleRequestOptionsType createVehicleRequestOptionsType() {
        return new VehicleRequestOptionsType();
    }

    /**
     * Create an instance of {@link CreditCardType }
     * 
     */
    public CreditCardType createCreditCardType() {
        return new CreditCardType();
    }

    /**
     * Create an instance of {@link ResortAreaType }
     * 
     */
    public ResortAreaType createResortAreaType() {
        return new ResortAreaType();
    }

    /**
     * Create an instance of {@link PaymentHistoryType }
     * 
     */
    public PaymentHistoryType createPaymentHistoryType() {
        return new PaymentHistoryType();
    }

    /**
     * Create an instance of {@link DestinationOptionsType }
     * 
     */
    public DestinationOptionsType createDestinationOptionsType() {
        return new DestinationOptionsType();
    }

    /**
     * Create an instance of {@link AgencyType }
     * 
     */
    public AgencyType createAgencyType() {
        return new AgencyType();
    }

    /**
     * Create an instance of {@link TravelClubType }
     * 
     */
    public TravelClubType createTravelClubType() {
        return new TravelClubType();
    }

    /**
     * Create an instance of {@link HotelRequestOptionsType }
     * 
     */
    public HotelRequestOptionsType createHotelRequestOptionsType() {
        return new HotelRequestOptionsType();
    }

    /**
     * Create an instance of {@link AgentType }
     * 
     */
    public AgentType createAgentType() {
        return new AgentType();
    }

    /**
     * Create an instance of {@link PriceType }
     * 
     */
    public PriceType createPriceType() {
        return new PriceType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link FlightPreferencesType }
     * 
     */
    public FlightPreferencesType createFlightPreferencesType() {
        return new FlightPreferencesType();
    }

    /**
     * Create an instance of {@link MultiDestSearchCriteriaType }
     * 
     */
    public MultiDestSearchCriteriaType createMultiDestSearchCriteriaType() {
        return new MultiDestSearchCriteriaType();
    }

}
