//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.20 at 04:31:23 PM PDT 
//


package com.kcdataservices.affiliate.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://affiliate.kcdataservices.com/common}paxId"/>
 *         &lt;element ref="{http://affiliate.kcdataservices.com/common}roomNumber"/>
 *         &lt;element ref="{http://affiliate.kcdataservices.com/common}ageCode"/>
 *         &lt;element ref="{http://affiliate.kcdataservices.com/common}age" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "paxId",
    "roomNumber",
    "ageCode",
    "age"
})
@XmlRootElement(name = "passenger")
public class Passenger {

    protected byte paxId;
    protected byte roomNumber;
    @XmlElement(required = true)
    protected String ageCode;
    protected Byte age;

    /**
     * Gets the value of the paxId property.
     * 
     */
    public byte getPaxId() {
        return paxId;
    }

    /**
     * Sets the value of the paxId property.
     * 
     */
    public void setPaxId(byte value) {
        this.paxId = value;
    }

    /**
     * Gets the value of the roomNumber property.
     * 
     */
    public byte getRoomNumber() {
        return roomNumber;
    }

    /**
     * Sets the value of the roomNumber property.
     * 
     */
    public void setRoomNumber(byte value) {
        this.roomNumber = value;
    }

    /**
     * Gets the value of the ageCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgeCode() {
        return ageCode;
    }

    /**
     * Sets the value of the ageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgeCode(String value) {
        this.ageCode = value;
    }

    /**
     * Gets the value of the age property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setAge(Byte value) {
        this.age = value;
    }

}
