//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 05:31:24 PM PST 
//


package com.kcdataservices.affiliate.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Passenger type to hold the passenger details
 * 
 * <p>Java class for PassengerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PassengerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="paxId" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *         &lt;element name="roomNumber" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
 *         &lt;element name="ageCode" type="{http://affiliate.kcdataservices.com/common}AgeCodeType"/>
 *         &lt;element name="age" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedByte">
 *               &lt;minInclusive value="2"/>
 *               &lt;maxInclusive value="17"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PassengerType", propOrder = {
    "paxId",
    "roomNumber",
    "ageCode",
    "age"
})
public class PassengerType {

    @XmlSchemaType(name = "unsignedByte")
    protected short paxId;
    @XmlSchemaType(name = "unsignedByte")
    protected Short roomNumber;
    @XmlElement(required = true)
    protected AgeCodeType ageCode;
    protected Short age;

    /**
     * Gets the value of the paxId property.
     * 
     */
    public short getPaxId() {
        return paxId;
    }

    /**
     * Sets the value of the paxId property.
     * 
     */
    public void setPaxId(short value) {
        this.paxId = value;
    }

    /**
     * Gets the value of the roomNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getRoomNumber() {
        return roomNumber;
    }

    /**
     * Sets the value of the roomNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setRoomNumber(Short value) {
        this.roomNumber = value;
    }

    /**
     * Gets the value of the ageCode property.
     * 
     * @return
     *     possible object is
     *     {@link AgeCodeType }
     *     
     */
    public AgeCodeType getAgeCode() {
        return ageCode;
    }

    /**
     * Sets the value of the ageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgeCodeType }
     *     
     */
    public void setAgeCode(AgeCodeType value) {
        this.ageCode = value;
    }

    /**
     * Gets the value of the age property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setAge(Short value) {
        this.age = value;
    }

}
