//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 05:31:24 PM PST 
//


package com.kcdataservices.affiliate.common;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Represents the price of a component
 * 
 * <p>Java class for PriceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PriceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fullOccupancyPrice" type="{http://affiliate.kcdataservices.com/common}AmountType"/>
 *         &lt;element name="perPersonPrice" type="{http://affiliate.kcdataservices.com/common}AmountType"/>
 *         &lt;element name="promoSavings" type="{http://affiliate.kcdataservices.com/common}AmountType"/>
 *         &lt;element name="basePrice" type="{http://affiliate.kcdataservices.com/common}AmountType" minOccurs="0"/>
 *         &lt;element name="usTax" type="{http://affiliate.kcdataservices.com/common}AmountType" minOccurs="0"/>
 *         &lt;element name="foreignTax" type="{http://affiliate.kcdataservices.com/common}AmountType" minOccurs="0"/>
 *         &lt;element name="airportFee" type="{http://affiliate.kcdataservices.com/common}AmountType" minOccurs="0"/>
 *         &lt;element name="totalTax" type="{http://affiliate.kcdataservices.com/common}AmountType" minOccurs="0"/>
 *         &lt;element name="commissionPercent" type="{http://affiliate.kcdataservices.com/common}AmountType" minOccurs="0"/>
 *         &lt;element name="commissionAmount" type="{http://affiliate.kcdataservices.com/common}AmountType" minOccurs="0"/>
 *         &lt;element name="paxTypePriceBreakup" type="{http://affiliate.kcdataservices.com/common}AmountType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PriceType", propOrder = {
    "fullOccupancyPrice",
    "perPersonPrice",
    "promoSavings",
    "basePrice",
    "usTax",
    "foreignTax",
    "airportFee",
    "totalTax",
    "commissionPercent",
    "commissionAmount",
    "paxTypePriceBreakup"
})
public class PriceType {

    protected double fullOccupancyPrice;
    protected double perPersonPrice;
    protected double promoSavings;
    protected Double basePrice;
    protected Double usTax;
    protected Double foreignTax;
    protected Double airportFee;
    protected Double totalTax;
    protected Double commissionPercent;
    protected Double commissionAmount;
    @XmlElement(type = Double.class)
    protected List<Double> paxTypePriceBreakup;

    /**
     * Gets the value of the fullOccupancyPrice property.
     * 
     */
    public double getFullOccupancyPrice() {
        return fullOccupancyPrice;
    }

    /**
     * Sets the value of the fullOccupancyPrice property.
     * 
     */
    public void setFullOccupancyPrice(double value) {
        this.fullOccupancyPrice = value;
    }

    /**
     * Gets the value of the perPersonPrice property.
     * 
     */
    public double getPerPersonPrice() {
        return perPersonPrice;
    }

    /**
     * Sets the value of the perPersonPrice property.
     * 
     */
    public void setPerPersonPrice(double value) {
        this.perPersonPrice = value;
    }

    /**
     * Gets the value of the promoSavings property.
     * 
     */
    public double getPromoSavings() {
        return promoSavings;
    }

    /**
     * Sets the value of the promoSavings property.
     * 
     */
    public void setPromoSavings(double value) {
        this.promoSavings = value;
    }

    /**
     * Gets the value of the basePrice property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBasePrice() {
        return basePrice;
    }

    /**
     * Sets the value of the basePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBasePrice(Double value) {
        this.basePrice = value;
    }

    /**
     * Gets the value of the usTax property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getUsTax() {
        return usTax;
    }

    /**
     * Sets the value of the usTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setUsTax(Double value) {
        this.usTax = value;
    }

    /**
     * Gets the value of the foreignTax property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getForeignTax() {
        return foreignTax;
    }

    /**
     * Sets the value of the foreignTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setForeignTax(Double value) {
        this.foreignTax = value;
    }

    /**
     * Gets the value of the airportFee property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAirportFee() {
        return airportFee;
    }

    /**
     * Sets the value of the airportFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAirportFee(Double value) {
        this.airportFee = value;
    }

    /**
     * Gets the value of the totalTax property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTotalTax() {
        return totalTax;
    }

    /**
     * Sets the value of the totalTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTotalTax(Double value) {
        this.totalTax = value;
    }

    /**
     * Gets the value of the commissionPercent property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCommissionPercent() {
        return commissionPercent;
    }

    /**
     * Sets the value of the commissionPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCommissionPercent(Double value) {
        this.commissionPercent = value;
    }

    /**
     * Gets the value of the commissionAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCommissionAmount() {
        return commissionAmount;
    }

    /**
     * Sets the value of the commissionAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCommissionAmount(Double value) {
        this.commissionAmount = value;
    }

    /**
     * Gets the value of the paxTypePriceBreakup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paxTypePriceBreakup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaxTypePriceBreakup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Double }
     * 
     * 
     */
    public List<Double> getPaxTypePriceBreakup() {
        if (paxTypePriceBreakup == null) {
            paxTypePriceBreakup = new ArrayList<Double>();
        }
        return this.paxTypePriceBreakup;
    }

}
