//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 05:31:24 PM PST 
//


package com.kcdataservices.affiliate.common;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * SearchCriteria to hold all the search options
 * 
 * <p>Java class for SearchCriteriaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchCriteriaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="gateway" type="{http://affiliate.kcdataservices.com/common}CityCodeType"/>
 *         &lt;element name="departureDate" type="{http://affiliate.kcdataservices.com/common}DateType"/>
 *         &lt;element name="promotions" type="{http://affiliate.kcdataservices.com/common}PromotionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="occupancy" type="{http://affiliate.kcdataservices.com/common}OccupancyType"/>
 *         &lt;element name="destinationOptions" type="{http://affiliate.kcdataservices.com/common}DestinationOptionsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchCriteriaType", propOrder = {
    "gateway",
    "departureDate",
    "promotions",
    "occupancy",
    "destinationOptions"
})
public class SearchCriteriaType {

    @XmlElement(required = true)
    protected String gateway;
    @XmlElement(required = true)
    protected XMLGregorianCalendar departureDate;
    protected List<PromotionType> promotions;
    @XmlElement(required = true)
    protected OccupancyType occupancy;
    @XmlElement(required = true)
    protected DestinationOptionsType destinationOptions;

    /**
     * Gets the value of the gateway property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGateway() {
        return gateway;
    }

    /**
     * Sets the value of the gateway property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGateway(String value) {
        this.gateway = value;
    }

    /**
     * Gets the value of the departureDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDepartureDate() {
        return departureDate;
    }

    /**
     * Sets the value of the departureDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDepartureDate(XMLGregorianCalendar value) {
        this.departureDate = value;
    }

    /**
     * Gets the value of the promotions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the promotions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPromotions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PromotionType }
     * 
     * 
     */
    public List<PromotionType> getPromotions() {
        if (promotions == null) {
            promotions = new ArrayList<PromotionType>();
        }
        return this.promotions;
    }

    /**
     * Gets the value of the occupancy property.
     * 
     * @return
     *     possible object is
     *     {@link OccupancyType }
     *     
     */
    public OccupancyType getOccupancy() {
        return occupancy;
    }

    /**
     * Sets the value of the occupancy property.
     * 
     * @param value
     *     allowed object is
     *     {@link OccupancyType }
     *     
     */
    public void setOccupancy(OccupancyType value) {
        this.occupancy = value;
    }

    /**
     * Gets the value of the destinationOptions property.
     * 
     * @return
     *     possible object is
     *     {@link DestinationOptionsType }
     *     
     */
    public DestinationOptionsType getDestinationOptions() {
        return destinationOptions;
    }

    /**
     * Sets the value of the destinationOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link DestinationOptionsType }
     *     
     */
    public void setDestinationOptions(DestinationOptionsType value) {
        this.destinationOptions = value;
    }

}
