//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 05:31:24 PM PST 
//


package com.kcdataservices.affiliate.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Identifies the Vehicle search options
 * 
 * <p>Java class for VehicleRequestOptionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VehicleRequestOptionsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pickupLocation" type="{http://affiliate.kcdataservices.com/common}CityCodeType" minOccurs="0"/>
 *         &lt;element name="dropoffLocation" type="{http://affiliate.kcdataservices.com/common}CityCodeType" minOccurs="0"/>
 *         &lt;element name="pickupDateTime" type="{http://affiliate.kcdataservices.com/common}DateTimeType" minOccurs="0"/>
 *         &lt;element name="dropoffDateTime" type="{http://affiliate.kcdataservices.com/common}DateTimeType" minOccurs="0"/>
 *         &lt;element name="vendorCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="vehicleClass" type="{http://affiliate.kcdataservices.com/common}VehicleClassType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VehicleRequestOptionsType", propOrder = {
    "pickupLocation",
    "dropoffLocation",
    "pickupDateTime",
    "dropoffDateTime",
    "vendorCode",
    "vehicleClass"
})
public class VehicleRequestOptionsType {

    protected String pickupLocation;
    protected String dropoffLocation;
    protected XMLGregorianCalendar pickupDateTime;
    protected XMLGregorianCalendar dropoffDateTime;
    protected String vendorCode;
    protected VehicleClassType vehicleClass;

    /**
     * Gets the value of the pickupLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPickupLocation() {
        return pickupLocation;
    }

    /**
     * Sets the value of the pickupLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPickupLocation(String value) {
        this.pickupLocation = value;
    }

    /**
     * Gets the value of the dropoffLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDropoffLocation() {
        return dropoffLocation;
    }

    /**
     * Sets the value of the dropoffLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDropoffLocation(String value) {
        this.dropoffLocation = value;
    }

    /**
     * Gets the value of the pickupDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPickupDateTime() {
        return pickupDateTime;
    }

    /**
     * Sets the value of the pickupDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPickupDateTime(XMLGregorianCalendar value) {
        this.pickupDateTime = value;
    }

    /**
     * Gets the value of the dropoffDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDropoffDateTime() {
        return dropoffDateTime;
    }

    /**
     * Sets the value of the dropoffDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDropoffDateTime(XMLGregorianCalendar value) {
        this.dropoffDateTime = value;
    }

    /**
     * Gets the value of the vendorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorCode() {
        return vendorCode;
    }

    /**
     * Sets the value of the vendorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorCode(String value) {
        this.vendorCode = value;
    }

    /**
     * Gets the value of the vehicleClass property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleClassType }
     *     
     */
    public VehicleClassType getVehicleClass() {
        return vehicleClass;
    }

    /**
     * Sets the value of the vehicleClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleClassType }
     *     
     */
    public void setVehicleClass(VehicleClassType value) {
        this.vehicleClass = value;
    }

}
