//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.13 at 02:25:01 PM PDT 
//


package net.phenomenon.applevac.livedemo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="trip">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="departed" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="returned" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="departflight" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="returnflight" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="length" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="confirmation" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="hotel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="room" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="travelers">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="traveler" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="confirmation" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trip"
})
@XmlRootElement(name = "pasttrips")
public class Pasttrips {

    @XmlElement(required = true)
    protected Pasttrips.Trip trip;

    /**
     * Gets the value of the trip property.
     * 
     * @return
     *     possible object is
     *     {@link Pasttrips.Trip }
     *     
     */
    public Pasttrips.Trip getTrip() {
        return trip;
    }

    /**
     * Sets the value of the trip property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pasttrips.Trip }
     *     
     */
    public void setTrip(Pasttrips.Trip value) {
        this.trip = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="departed" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="returned" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="departflight" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="returnflight" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="length" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="confirmation" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="hotel" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="room" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="travelers">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="traveler" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="confirmation" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "departed",
        "returned",
        "departflight",
        "returnflight",
        "from",
        "to",
        "length",
        "confirmation",
        "hotel",
        "room",
        "travelers"
    })
    public static class Trip {

        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar departed;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar returned;
        @XmlElement(required = true)
        protected String departflight;
        @XmlElement(required = true)
        protected String returnflight;
        @XmlElement(required = true)
        protected String from;
        @XmlElement(required = true)
        protected String to;
        @XmlElement(required = true)
        protected String length;
        protected long confirmation;
        @XmlElement(required = true)
        protected String hotel;
        @XmlElement(required = true)
        protected String room;
        @XmlElement(required = true)
        protected Pasttrips.Trip.Travelers travelers;

        /**
         * Gets the value of the departed property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDeparted() {
            return departed;
        }

        /**
         * Sets the value of the departed property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDeparted(XMLGregorianCalendar value) {
            this.departed = value;
        }

        /**
         * Gets the value of the returned property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getReturned() {
            return returned;
        }

        /**
         * Sets the value of the returned property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setReturned(XMLGregorianCalendar value) {
            this.returned = value;
        }

        /**
         * Gets the value of the departflight property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDepartflight() {
            return departflight;
        }

        /**
         * Sets the value of the departflight property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDepartflight(String value) {
            this.departflight = value;
        }

        /**
         * Gets the value of the returnflight property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReturnflight() {
            return returnflight;
        }

        /**
         * Sets the value of the returnflight property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReturnflight(String value) {
            this.returnflight = value;
        }

        /**
         * Gets the value of the from property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFrom() {
            return from;
        }

        /**
         * Sets the value of the from property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFrom(String value) {
            this.from = value;
        }

        /**
         * Gets the value of the to property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTo() {
            return to;
        }

        /**
         * Sets the value of the to property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTo(String value) {
            this.to = value;
        }

        /**
         * Gets the value of the length property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLength() {
            return length;
        }

        /**
         * Sets the value of the length property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLength(String value) {
            this.length = value;
        }

        /**
         * Gets the value of the confirmation property.
         * 
         */
        public long getConfirmation() {
            return confirmation;
        }

        /**
         * Sets the value of the confirmation property.
         * 
         */
        public void setConfirmation(long value) {
            this.confirmation = value;
        }

        /**
         * Gets the value of the hotel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHotel() {
            return hotel;
        }

        /**
         * Sets the value of the hotel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHotel(String value) {
            this.hotel = value;
        }

        /**
         * Gets the value of the room property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRoom() {
            return room;
        }

        /**
         * Sets the value of the room property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRoom(String value) {
            this.room = value;
        }

        /**
         * Gets the value of the travelers property.
         * 
         * @return
         *     possible object is
         *     {@link Pasttrips.Trip.Travelers }
         *     
         */
        public Pasttrips.Trip.Travelers getTravelers() {
            return travelers;
        }

        /**
         * Sets the value of the travelers property.
         * 
         * @param value
         *     allowed object is
         *     {@link Pasttrips.Trip.Travelers }
         *     
         */
        public void setTravelers(Pasttrips.Trip.Travelers value) {
            this.travelers = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="traveler" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="confirmation" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "traveler"
        })
        public static class Travelers {

            protected List<Pasttrips.Trip.Travelers.Traveler> traveler;

            /**
             * Gets the value of the traveler property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the traveler property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTraveler().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Pasttrips.Trip.Travelers.Traveler }
             * 
             * 
             */
            public List<Pasttrips.Trip.Travelers.Traveler> getTraveler() {
                if (traveler == null) {
                    traveler = new ArrayList<Pasttrips.Trip.Travelers.Traveler>();
                }
                return this.traveler;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="confirmation" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "name",
                "confirmation",
                "type"
            })
            public static class Traveler {

                @XmlElement(required = true)
                protected String name;
                protected int confirmation;
                @XmlElement(required = true)
                protected String type;

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the confirmation property.
                 * 
                 */
                public int getConfirmation() {
                    return confirmation;
                }

                /**
                 * Sets the value of the confirmation property.
                 * 
                 */
                public void setConfirmation(int value) {
                    this.confirmation = value;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setType(String value) {
                    this.type = value;
                }

            }

        }

    }

}
