//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 05:31:18 PM PST 
//


package com.kcdataservices.affiliate.hotels;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.kcdataservices.affiliate.common.OccupancyType;


/**
 * Indicates the Hotels availability
 * 
 * <p>Java class for HotelAvailabilityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HotelAvailabilityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="destination" type="{http://affiliate.kcdataservices.com/common}CityCodeType"/>
 *         &lt;element name="checkInDate" type="{http://affiliate.kcdataservices.com/common}DateType"/>
 *         &lt;element name="checkOutDate" type="{http://affiliate.kcdataservices.com/common}DateType"/>
 *         &lt;element name="occupancy" type="{http://affiliate.kcdataservices.com/common}OccupancyType"/>
 *         &lt;element name="noOfOptions" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *         &lt;element name="hotelOption" type="{http://affiliate.kcdataservices.com/hotels}HotelOptionType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HotelAvailabilityType", propOrder = {
    "destination",
    "checkInDate",
    "checkOutDate",
    "occupancy",
    "noOfOptions",
    "hotelOption"
})
public class HotelAvailabilityType {

    @XmlElement(required = true)
    protected String destination;
    @XmlElement(required = true)
    protected XMLGregorianCalendar checkInDate;
    @XmlElement(required = true)
    protected XMLGregorianCalendar checkOutDate;
    @XmlElement(required = true)
    protected OccupancyType occupancy;
    @XmlSchemaType(name = "unsignedByte")
    protected short noOfOptions;
    protected List<HotelOptionType> hotelOption;

    /**
     * Gets the value of the destination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestination(String value) {
        this.destination = value;
    }

    /**
     * Gets the value of the checkInDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCheckInDate() {
        return checkInDate;
    }

    /**
     * Sets the value of the checkInDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCheckInDate(XMLGregorianCalendar value) {
        this.checkInDate = value;
    }

    /**
     * Gets the value of the checkOutDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCheckOutDate() {
        return checkOutDate;
    }

    /**
     * Sets the value of the checkOutDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCheckOutDate(XMLGregorianCalendar value) {
        this.checkOutDate = value;
    }

    /**
     * Gets the value of the occupancy property.
     * 
     * @return
     *     possible object is
     *     {@link OccupancyType }
     *     
     */
    public OccupancyType getOccupancy() {
        return occupancy;
    }

    /**
     * Sets the value of the occupancy property.
     * 
     * @param value
     *     allowed object is
     *     {@link OccupancyType }
     *     
     */
    public void setOccupancy(OccupancyType value) {
        this.occupancy = value;
    }

    /**
     * Gets the value of the noOfOptions property.
     * 
     */
    public short getNoOfOptions() {
        return noOfOptions;
    }

    /**
     * Sets the value of the noOfOptions property.
     * 
     */
    public void setNoOfOptions(short value) {
        this.noOfOptions = value;
    }

    /**
     * Gets the value of the hotelOption property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hotelOption property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHotelOption().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HotelOptionType }
     * 
     * 
     */
    public List<HotelOptionType> getHotelOption() {
        if (hotelOption == null) {
            hotelOption = new ArrayList<HotelOptionType>();
        }
        return this.hotelOption;
    }

}
