//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 05:31:18 PM PST 
//


package com.kcdataservices.affiliate.hotels;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.kcdataservices.affiliate.hotels package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.kcdataservices.affiliate.hotels
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HotelAvailabilityType }
     * 
     */
    public HotelAvailabilityType createHotelAvailabilityType() {
        return new HotelAvailabilityType();
    }

    /**
     * Create an instance of {@link HotelOptionType }
     * 
     */
    public HotelOptionType createHotelOptionType() {
        return new HotelOptionType();
    }

    /**
     * Create an instance of {@link VendorServiceType }
     * 
     */
    public VendorServiceType createVendorServiceType() {
        return new VendorServiceType();
    }

    /**
     * Create an instance of {@link AmenityType }
     * 
     */
    public AmenityType createAmenityType() {
        return new AmenityType();
    }

    /**
     * Create an instance of {@link RoomType }
     * 
     */
    public RoomType createRoomType() {
        return new RoomType();
    }

    /**
     * Create an instance of {@link RatePlanType }
     * 
     */
    public RatePlanType createRatePlanType() {
        return new RatePlanType();
    }

    /**
     * Create an instance of {@link SelectedHotelType }
     * 
     */
    public SelectedHotelType createSelectedHotelType() {
        return new SelectedHotelType();
    }

    /**
     * Create an instance of {@link RoomCategoryType }
     * 
     */
    public RoomCategoryType createRoomCategoryType() {
        return new RoomCategoryType();
    }

}
