//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 05:31:18 PM PST 
//


package com.kcdataservices.affiliate.hotels;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.kcdataservices.affiliate.common.OccupancyType;


/**
 * Represents the complete details of the Hotel selected
 * 
 * <p>Java class for SelectedHotelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SelectedHotelType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://affiliate.kcdataservices.com/hotels}HotelOptionType">
 *       &lt;sequence>
 *         &lt;element name="destination" type="{http://affiliate.kcdataservices.com/common}CityCodeType"/>
 *         &lt;element name="checkInDate" type="{http://affiliate.kcdataservices.com/common}DateType"/>
 *         &lt;element name="checkOutDate" type="{http://affiliate.kcdataservices.com/common}DateType"/>
 *         &lt;element name="occupancy" type="{http://affiliate.kcdataservices.com/common}OccupancyType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SelectedHotelType", propOrder = {
    "destination",
    "checkInDate",
    "checkOutDate",
    "occupancy"
})
public class SelectedHotelType
    extends HotelOptionType
{

    @XmlElement(required = true)
    protected String destination;
    @XmlElement(required = true)
    protected XMLGregorianCalendar checkInDate;
    @XmlElement(required = true)
    protected XMLGregorianCalendar checkOutDate;
    @XmlElement(required = true)
    protected OccupancyType occupancy;

    /**
     * Gets the value of the destination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestination(String value) {
        this.destination = value;
    }

    /**
     * Gets the value of the checkInDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCheckInDate() {
        return checkInDate;
    }

    /**
     * Sets the value of the checkInDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCheckInDate(XMLGregorianCalendar value) {
        this.checkInDate = value;
    }

    /**
     * Gets the value of the checkOutDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCheckOutDate() {
        return checkOutDate;
    }

    /**
     * Sets the value of the checkOutDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCheckOutDate(XMLGregorianCalendar value) {
        this.checkOutDate = value;
    }

    /**
     * Gets the value of the occupancy property.
     * 
     * @return
     *     possible object is
     *     {@link OccupancyType }
     *     
     */
    public OccupancyType getOccupancy() {
        return occupancy;
    }

    /**
     * Sets the value of the occupancy property.
     * 
     * @param value
     *     allowed object is
     *     {@link OccupancyType }
     *     
     */
    public void setOccupancy(OccupancyType value) {
        this.occupancy = value;
    }

}
