//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 04:20:56 PM PST 
//


package com.kcdataservices.affiliate.services;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Represents the selected service details
 * 
 * <p>Java class for SelectedServiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SelectedServiceType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://affiliate.kcdataservices.com/services}ServiceType">
 *       &lt;sequence>
 *         &lt;element name="selectedDate" type="{http://affiliate.kcdataservices.com/common}DateType" minOccurs="0"/>
 *         &lt;element name="adultQty" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
 *         &lt;element name="child1Qty" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
 *         &lt;element name="child2Qty" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
 *         &lt;element name="child3Qty" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
 *         &lt;element name="guestAllocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="totalPrice" type="{http://affiliate.kcdataservices.com/common}AmountType" minOccurs="0"/>
 *         &lt;element name="travelFromDate" type="{http://affiliate.kcdataservices.com/common}DateType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SelectedServiceType", propOrder = {
    "selectedDate",
    "adultQty",
    "child1Qty",
    "child2Qty",
    "child3Qty",
    "guestAllocation",
    "totalPrice",
    "travelFromDate"
})
public class SelectedServiceType
    extends ServiceType
{

    protected XMLGregorianCalendar selectedDate;
    protected Byte adultQty;
    protected Byte child1Qty;
    protected Byte child2Qty;
    protected Byte child3Qty;
    protected String guestAllocation;
    protected Double totalPrice;
    protected XMLGregorianCalendar travelFromDate;

    /**
     * Gets the value of the selectedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSelectedDate() {
        return selectedDate;
    }

    /**
     * Sets the value of the selectedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSelectedDate(XMLGregorianCalendar value) {
        this.selectedDate = value;
    }

    /**
     * Gets the value of the adultQty property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getAdultQty() {
        return adultQty;
    }

    /**
     * Sets the value of the adultQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setAdultQty(Byte value) {
        this.adultQty = value;
    }

    /**
     * Gets the value of the child1Qty property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getChild1Qty() {
        return child1Qty;
    }

    /**
     * Sets the value of the child1Qty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setChild1Qty(Byte value) {
        this.child1Qty = value;
    }

    /**
     * Gets the value of the child2Qty property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getChild2Qty() {
        return child2Qty;
    }

    /**
     * Sets the value of the child2Qty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setChild2Qty(Byte value) {
        this.child2Qty = value;
    }

    /**
     * Gets the value of the child3Qty property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getChild3Qty() {
        return child3Qty;
    }

    /**
     * Sets the value of the child3Qty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setChild3Qty(Byte value) {
        this.child3Qty = value;
    }

    /**
     * Gets the value of the guestAllocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuestAllocation() {
        return guestAllocation;
    }

    /**
     * Sets the value of the guestAllocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuestAllocation(String value) {
        this.guestAllocation = value;
    }

    /**
     * Gets the value of the totalPrice property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTotalPrice() {
        return totalPrice;
    }

    /**
     * Sets the value of the totalPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTotalPrice(Double value) {
        this.totalPrice = value;
    }

    /**
     * Gets the value of the travelFromDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTravelFromDate() {
        return travelFromDate;
    }

    /**
     * Sets the value of the travelFromDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTravelFromDate(XMLGregorianCalendar value) {
        this.travelFromDate = value;
    }

}
