//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 04:20:56 PM PST 
//


package com.kcdataservices.affiliate.services;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.kcdataservices.affiliate.common.BooleanFlagType;


/**
 * Represents the Service details
 * 
 * <p>Java class for ServiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="gateway" type="{http://affiliate.kcdataservices.com/common}CityCodeType" minOccurs="0"/>
 *         &lt;element name="destination" type="{http://affiliate.kcdataservices.com/common}CityCodeType" minOccurs="0"/>
 *         &lt;element name="adultPrice" type="{http://affiliate.kcdataservices.com/common}AmountType" minOccurs="0"/>
 *         &lt;element name="childPrices" type="{http://affiliate.kcdataservices.com/common}AmountType" maxOccurs="3" minOccurs="0"/>
 *         &lt;element name="maxQuantityAllowed" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="mandatory" type="{http://affiliate.kcdataservices.com/common}BooleanFlagType" minOccurs="0"/>
 *         &lt;element name="free" type="{http://affiliate.kcdataservices.com/common}BooleanFlagType" minOccurs="0"/>
 *         &lt;element name="occupancyBased" type="{http://affiliate.kcdataservices.com/common}BooleanFlagType" minOccurs="0"/>
 *         &lt;element name="allOrNothing" type="{http://affiliate.kcdataservices.com/common}BooleanFlagType" minOccurs="0"/>
 *         &lt;element name="weightBased" type="{http://affiliate.kcdataservices.com/common}BooleanFlagType" minOccurs="0"/>
 *         &lt;element name="tierBased" type="{http://affiliate.kcdataservices.com/common}BooleanFlagType" minOccurs="0"/>
 *         &lt;element name="availableDates" type="{http://affiliate.kcdataservices.com/common}DateType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="flightCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="hotelCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceType", propOrder = {
    "code",
    "name",
    "description",
    "gateway",
    "destination",
    "adultPrice",
    "childPrices",
    "maxQuantityAllowed",
    "mandatory",
    "free",
    "occupancyBased",
    "allOrNothing",
    "weightBased",
    "tierBased",
    "availableDates",
    "flightCode",
    "hotelCode"
})
@XmlSeeAlso({
    SelectedServiceType.class
})
public class ServiceType {

    @XmlElement(required = true)
    protected String code;
    @XmlElement(required = true)
    protected String name;
    protected String description;
    protected String gateway;
    protected String destination;
    protected Double adultPrice;
    @XmlElement(type = Double.class)
    protected List<Double> childPrices;
    protected byte maxQuantityAllowed;
    protected BooleanFlagType mandatory;
    protected BooleanFlagType free;
    protected BooleanFlagType occupancyBased;
    protected BooleanFlagType allOrNothing;
    protected BooleanFlagType weightBased;
    protected BooleanFlagType tierBased;
    protected List<XMLGregorianCalendar> availableDates;
    protected String flightCode;
    protected String hotelCode;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "anySimpleType")
    protected String id;

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the gateway property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGateway() {
        return gateway;
    }

    /**
     * Sets the value of the gateway property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGateway(String value) {
        this.gateway = value;
    }

    /**
     * Gets the value of the destination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestination(String value) {
        this.destination = value;
    }

    /**
     * Gets the value of the adultPrice property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAdultPrice() {
        return adultPrice;
    }

    /**
     * Sets the value of the adultPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAdultPrice(Double value) {
        this.adultPrice = value;
    }

    /**
     * Gets the value of the childPrices property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the childPrices property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChildPrices().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Double }
     * 
     * 
     */
    public List<Double> getChildPrices() {
        if (childPrices == null) {
            childPrices = new ArrayList<Double>();
        }
        return this.childPrices;
    }

    /**
     * Gets the value of the maxQuantityAllowed property.
     * 
     */
    public byte getMaxQuantityAllowed() {
        return maxQuantityAllowed;
    }

    /**
     * Sets the value of the maxQuantityAllowed property.
     * 
     */
    public void setMaxQuantityAllowed(byte value) {
        this.maxQuantityAllowed = value;
    }

    /**
     * Gets the value of the mandatory property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanFlagType }
     *     
     */
    public BooleanFlagType getMandatory() {
        return mandatory;
    }

    /**
     * Sets the value of the mandatory property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanFlagType }
     *     
     */
    public void setMandatory(BooleanFlagType value) {
        this.mandatory = value;
    }

    /**
     * Gets the value of the free property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanFlagType }
     *     
     */
    public BooleanFlagType getFree() {
        return free;
    }

    /**
     * Sets the value of the free property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanFlagType }
     *     
     */
    public void setFree(BooleanFlagType value) {
        this.free = value;
    }

    /**
     * Gets the value of the occupancyBased property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanFlagType }
     *     
     */
    public BooleanFlagType getOccupancyBased() {
        return occupancyBased;
    }

    /**
     * Sets the value of the occupancyBased property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanFlagType }
     *     
     */
    public void setOccupancyBased(BooleanFlagType value) {
        this.occupancyBased = value;
    }

    /**
     * Gets the value of the allOrNothing property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanFlagType }
     *     
     */
    public BooleanFlagType getAllOrNothing() {
        return allOrNothing;
    }

    /**
     * Sets the value of the allOrNothing property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanFlagType }
     *     
     */
    public void setAllOrNothing(BooleanFlagType value) {
        this.allOrNothing = value;
    }

    /**
     * Gets the value of the weightBased property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanFlagType }
     *     
     */
    public BooleanFlagType getWeightBased() {
        return weightBased;
    }

    /**
     * Sets the value of the weightBased property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanFlagType }
     *     
     */
    public void setWeightBased(BooleanFlagType value) {
        this.weightBased = value;
    }

    /**
     * Gets the value of the tierBased property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanFlagType }
     *     
     */
    public BooleanFlagType getTierBased() {
        return tierBased;
    }

    /**
     * Sets the value of the tierBased property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanFlagType }
     *     
     */
    public void setTierBased(BooleanFlagType value) {
        this.tierBased = value;
    }

    /**
     * Gets the value of the availableDates property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the availableDates property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAvailableDates().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLGregorianCalendar }
     * 
     * 
     */
    public List<XMLGregorianCalendar> getAvailableDates() {
        if (availableDates == null) {
            availableDates = new ArrayList<XMLGregorianCalendar>();
        }
        return this.availableDates;
    }

    /**
     * Gets the value of the flightCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlightCode() {
        return flightCode;
    }

    /**
     * Sets the value of the flightCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlightCode(String value) {
        this.flightCode = value;
    }

    /**
     * Gets the value of the hotelCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHotelCode() {
        return hotelCode;
    }

    /**
     * Sets the value of the hotelCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHotelCode(String value) {
        this.hotelCode = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
