//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 04:20:56 PM PST 
//


package com.kcdataservices.affiliate.itinerary;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Represents the Guest Price BreakUp details
 * 
 * <p>Java class for GuestPriceBreakupType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GuestPriceBreakupType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="flightPrice" type="{http://affiliate.kcdataservices.com/common}AmountType" minOccurs="0"/>
 *         &lt;element name="hotelPrice" type="{http://affiliate.kcdataservices.com/common}AmountType" minOccurs="0"/>
 *         &lt;element name="vehiclePrice" type="{http://affiliate.kcdataservices.com/common}AmountType" minOccurs="0"/>
 *         &lt;element name="servicePrice" type="{http://affiliate.kcdataservices.com/common}AmountType" minOccurs="0"/>
 *         &lt;element name="insurancePrice" type="{http://affiliate.kcdataservices.com/common}AmountType" minOccurs="0"/>
 *         &lt;element name="basePrice" type="{http://affiliate.kcdataservices.com/common}AmountType" minOccurs="0"/>
 *         &lt;element name="taxPrice" type="{http://affiliate.kcdataservices.com/common}AmountType" minOccurs="0"/>
 *         &lt;element name="fees" type="{http://affiliate.kcdataservices.com/common}AmountType" minOccurs="0"/>
 *         &lt;element name="totalPrice" type="{http://affiliate.kcdataservices.com/common}AmountType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GuestPriceBreakupType", propOrder = {
    "flightPrice",
    "hotelPrice",
    "vehiclePrice",
    "servicePrice",
    "insurancePrice",
    "basePrice",
    "taxPrice",
    "fees",
    "totalPrice"
})
public class GuestPriceBreakupType {

    protected Double flightPrice;
    protected Double hotelPrice;
    protected Double vehiclePrice;
    protected Double servicePrice;
    protected Double insurancePrice;
    protected Double basePrice;
    protected Double taxPrice;
    protected Double fees;
    protected Double totalPrice;

    /**
     * Gets the value of the flightPrice property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getFlightPrice() {
        return flightPrice;
    }

    /**
     * Sets the value of the flightPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setFlightPrice(Double value) {
        this.flightPrice = value;
    }

    /**
     * Gets the value of the hotelPrice property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getHotelPrice() {
        return hotelPrice;
    }

    /**
     * Sets the value of the hotelPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setHotelPrice(Double value) {
        this.hotelPrice = value;
    }

    /**
     * Gets the value of the vehiclePrice property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getVehiclePrice() {
        return vehiclePrice;
    }

    /**
     * Sets the value of the vehiclePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setVehiclePrice(Double value) {
        this.vehiclePrice = value;
    }

    /**
     * Gets the value of the servicePrice property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getServicePrice() {
        return servicePrice;
    }

    /**
     * Sets the value of the servicePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setServicePrice(Double value) {
        this.servicePrice = value;
    }

    /**
     * Gets the value of the insurancePrice property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getInsurancePrice() {
        return insurancePrice;
    }

    /**
     * Sets the value of the insurancePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setInsurancePrice(Double value) {
        this.insurancePrice = value;
    }

    /**
     * Gets the value of the basePrice property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBasePrice() {
        return basePrice;
    }

    /**
     * Sets the value of the basePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBasePrice(Double value) {
        this.basePrice = value;
    }

    /**
     * Gets the value of the taxPrice property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTaxPrice() {
        return taxPrice;
    }

    /**
     * Sets the value of the taxPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTaxPrice(Double value) {
        this.taxPrice = value;
    }

    /**
     * Gets the value of the fees property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getFees() {
        return fees;
    }

    /**
     * Sets the value of the fees property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setFees(Double value) {
        this.fees = value;
    }

    /**
     * Gets the value of the totalPrice property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTotalPrice() {
        return totalPrice;
    }

    /**
     * Sets the value of the totalPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTotalPrice(Double value) {
        this.totalPrice = value;
    }

}
