//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 04:20:56 PM PST 
//


package com.kcdataservices.affiliate.itinerary;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.kcdataservices.affiliate.common.AgeCodeType;


/**
 * Represents the Guest Details
 * 
 * <p>Java class for GuestInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GuestInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="title">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Mr"/>
 *               &lt;enumeration value="Mrs"/>
 *               &lt;enumeration value="Ms"/>
 *               &lt;enumeration value="Miss"/>
 *               &lt;enumeration value="Mstr"/>
 *               &lt;enumeration value="MR"/>
 *               &lt;enumeration value="MRS"/>
 *               &lt;enumeration value="MS"/>
 *               &lt;enumeration value="MISS"/>
 *               &lt;enumeration value="MSTR"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="middleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gender">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="1"/>
 *               &lt;enumeration value="M"/>
 *               &lt;enumeration value="F"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ageCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://affiliate.kcdataservices.com/common}AgeCodeType">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="age" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
 *         &lt;element name="dateOfBirth" type="{http://affiliate.kcdataservices.com/common}DateType"/>
 *         &lt;element name="phoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="emailId" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[^@]+@[^\.]+\..+"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="parentGuestId" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
 *         &lt;element name="emergencyContactName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="emergencyContactPhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="frequentFlyerNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="passportInfo" type="{http://affiliate.kcdataservices.com/itinerary}PassportInfoType" minOccurs="0"/>
 *         &lt;element name="airRemarks" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="0"/>
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="hotelRemarks" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="0"/>
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="cruiseRemarks" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="0"/>
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="mealRequest" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="0"/>
 *               &lt;maxLength value="63"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="airRequest" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="0"/>
 *               &lt;maxLength value="63"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="groundRequest" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="0"/>
 *               &lt;maxLength value="63"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="cateringRequest" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="0"/>
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="seatPreference" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="0"/>
 *               &lt;maxLength value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="priceBreakup" type="{http://affiliate.kcdataservices.com/itinerary}GuestPriceBreakupType" minOccurs="0"/>
 *         &lt;element name="pnrNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="redressNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="weight" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GuestInfoType", propOrder = {
    "id",
    "title",
    "firstName",
    "middleName",
    "lastName",
    "gender",
    "ageCode",
    "age",
    "dateOfBirth",
    "phoneNumber",
    "emailId",
    "parentGuestId",
    "emergencyContactName",
    "emergencyContactPhone",
    "frequentFlyerNo",
    "passportInfo",
    "airRemarks",
    "hotelRemarks",
    "cruiseRemarks",
    "mealRequest",
    "airRequest",
    "groundRequest",
    "cateringRequest",
    "seatPreference",
    "status",
    "priceBreakup",
    "pnrNumber",
    "redressNumber",
    "weight"
})
public class GuestInfoType {

    protected byte id;
    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected String firstName;
    protected String middleName;
    @XmlElement(required = true)
    protected String lastName;
    @XmlElement(required = true)
    protected String gender;
    @XmlElement(required = true)
    protected AgeCodeType ageCode;
    @XmlSchemaType(name = "unsignedByte")
    protected Short age;
    @XmlElement(required = true)
    protected XMLGregorianCalendar dateOfBirth;
    protected String phoneNumber;
    protected String emailId;
    protected Byte parentGuestId;
    protected String emergencyContactName;
    protected String emergencyContactPhone;
    protected String frequentFlyerNo;
    protected PassportInfoType passportInfo;
    protected String airRemarks;
    protected String hotelRemarks;
    protected String cruiseRemarks;
    protected String mealRequest;
    protected String airRequest;
    protected String groundRequest;
    protected String cateringRequest;
    protected String seatPreference;
    protected String status;
    protected GuestPriceBreakupType priceBreakup;
    protected String pnrNumber;
    protected String redressNumber;
    protected Byte weight;

    /**
     * Gets the value of the id property.
     * 
     */
    public byte getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(byte value) {
        this.id = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddleName(String value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the ageCode property.
     * 
     * @return
     *     possible object is
     *     {@link AgeCodeType }
     *     
     */
    public AgeCodeType getAgeCode() {
        return ageCode;
    }

    /**
     * Sets the value of the ageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgeCodeType }
     *     
     */
    public void setAgeCode(AgeCodeType value) {
        this.ageCode = value;
    }

    /**
     * Gets the value of the age property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setAge(Short value) {
        this.age = value;
    }

    /**
     * Gets the value of the dateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOfBirth(XMLGregorianCalendar value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the phoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Sets the value of the phoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneNumber(String value) {
        this.phoneNumber = value;
    }

    /**
     * Gets the value of the emailId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailId() {
        return emailId;
    }

    /**
     * Sets the value of the emailId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailId(String value) {
        this.emailId = value;
    }

    /**
     * Gets the value of the parentGuestId property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getParentGuestId() {
        return parentGuestId;
    }

    /**
     * Sets the value of the parentGuestId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setParentGuestId(Byte value) {
        this.parentGuestId = value;
    }

    /**
     * Gets the value of the emergencyContactName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmergencyContactName() {
        return emergencyContactName;
    }

    /**
     * Sets the value of the emergencyContactName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmergencyContactName(String value) {
        this.emergencyContactName = value;
    }

    /**
     * Gets the value of the emergencyContactPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmergencyContactPhone() {
        return emergencyContactPhone;
    }

    /**
     * Sets the value of the emergencyContactPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmergencyContactPhone(String value) {
        this.emergencyContactPhone = value;
    }

    /**
     * Gets the value of the frequentFlyerNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrequentFlyerNo() {
        return frequentFlyerNo;
    }

    /**
     * Sets the value of the frequentFlyerNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrequentFlyerNo(String value) {
        this.frequentFlyerNo = value;
    }

    /**
     * Gets the value of the passportInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PassportInfoType }
     *     
     */
    public PassportInfoType getPassportInfo() {
        return passportInfo;
    }

    /**
     * Sets the value of the passportInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PassportInfoType }
     *     
     */
    public void setPassportInfo(PassportInfoType value) {
        this.passportInfo = value;
    }

    /**
     * Gets the value of the airRemarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirRemarks() {
        return airRemarks;
    }

    /**
     * Sets the value of the airRemarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirRemarks(String value) {
        this.airRemarks = value;
    }

    /**
     * Gets the value of the hotelRemarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHotelRemarks() {
        return hotelRemarks;
    }

    /**
     * Sets the value of the hotelRemarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHotelRemarks(String value) {
        this.hotelRemarks = value;
    }

    /**
     * Gets the value of the cruiseRemarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCruiseRemarks() {
        return cruiseRemarks;
    }

    /**
     * Sets the value of the cruiseRemarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCruiseRemarks(String value) {
        this.cruiseRemarks = value;
    }

    /**
     * Gets the value of the mealRequest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMealRequest() {
        return mealRequest;
    }

    /**
     * Sets the value of the mealRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMealRequest(String value) {
        this.mealRequest = value;
    }

    /**
     * Gets the value of the airRequest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirRequest() {
        return airRequest;
    }

    /**
     * Sets the value of the airRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirRequest(String value) {
        this.airRequest = value;
    }

    /**
     * Gets the value of the groundRequest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroundRequest() {
        return groundRequest;
    }

    /**
     * Sets the value of the groundRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroundRequest(String value) {
        this.groundRequest = value;
    }

    /**
     * Gets the value of the cateringRequest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCateringRequest() {
        return cateringRequest;
    }

    /**
     * Sets the value of the cateringRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCateringRequest(String value) {
        this.cateringRequest = value;
    }

    /**
     * Gets the value of the seatPreference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeatPreference() {
        return seatPreference;
    }

    /**
     * Sets the value of the seatPreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeatPreference(String value) {
        this.seatPreference = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the priceBreakup property.
     * 
     * @return
     *     possible object is
     *     {@link GuestPriceBreakupType }
     *     
     */
    public GuestPriceBreakupType getPriceBreakup() {
        return priceBreakup;
    }

    /**
     * Sets the value of the priceBreakup property.
     * 
     * @param value
     *     allowed object is
     *     {@link GuestPriceBreakupType }
     *     
     */
    public void setPriceBreakup(GuestPriceBreakupType value) {
        this.priceBreakup = value;
    }

    /**
     * Gets the value of the pnrNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPnrNumber() {
        return pnrNumber;
    }

    /**
     * Sets the value of the pnrNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPnrNumber(String value) {
        this.pnrNumber = value;
    }

    /**
     * Gets the value of the redressNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRedressNumber() {
        return redressNumber;
    }

    /**
     * Sets the value of the redressNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRedressNumber(String value) {
        this.redressNumber = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setWeight(Byte value) {
        this.weight = value;
    }

}
