//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 04:20:56 PM PST 
//


package com.kcdataservices.affiliate.itinerary;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Represents the Itinerary Price
 * 
 * <p>Java class for ItineraryPriceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItineraryPriceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="totalPrice" type="{http://affiliate.kcdataservices.com/common}AmountType"/>
 *         &lt;element name="basePrice" type="{http://affiliate.kcdataservices.com/common}AmountType"/>
 *         &lt;element name="taxes" type="{http://affiliate.kcdataservices.com/common}AmountType"/>
 *         &lt;element name="fees" type="{http://affiliate.kcdataservices.com/common}AmountType"/>
 *         &lt;element name="promoSavings" type="{http://affiliate.kcdataservices.com/common}AmountType"/>
 *         &lt;element name="depositAmount" type="{http://affiliate.kcdataservices.com/common}AmountType" minOccurs="0"/>
 *         &lt;element name="depositDate" type="{http://affiliate.kcdataservices.com/common}DateType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItineraryPriceType", propOrder = {
    "totalPrice",
    "basePrice",
    "taxes",
    "fees",
    "promoSavings",
    "depositAmount",
    "depositDate"
})
public class ItineraryPriceType {

    protected double totalPrice;
    protected double basePrice;
    protected double taxes;
    protected double fees;
    protected double promoSavings;
    protected Double depositAmount;
    protected XMLGregorianCalendar depositDate;

    /**
     * Gets the value of the totalPrice property.
     * 
     */
    public double getTotalPrice() {
        return totalPrice;
    }

    /**
     * Sets the value of the totalPrice property.
     * 
     */
    public void setTotalPrice(double value) {
        this.totalPrice = value;
    }

    /**
     * Gets the value of the basePrice property.
     * 
     */
    public double getBasePrice() {
        return basePrice;
    }

    /**
     * Sets the value of the basePrice property.
     * 
     */
    public void setBasePrice(double value) {
        this.basePrice = value;
    }

    /**
     * Gets the value of the taxes property.
     * 
     */
    public double getTaxes() {
        return taxes;
    }

    /**
     * Sets the value of the taxes property.
     * 
     */
    public void setTaxes(double value) {
        this.taxes = value;
    }

    /**
     * Gets the value of the fees property.
     * 
     */
    public double getFees() {
        return fees;
    }

    /**
     * Sets the value of the fees property.
     * 
     */
    public void setFees(double value) {
        this.fees = value;
    }

    /**
     * Gets the value of the promoSavings property.
     * 
     */
    public double getPromoSavings() {
        return promoSavings;
    }

    /**
     * Sets the value of the promoSavings property.
     * 
     */
    public void setPromoSavings(double value) {
        this.promoSavings = value;
    }

    /**
     * Gets the value of the depositAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDepositAmount() {
        return depositAmount;
    }

    /**
     * Sets the value of the depositAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDepositAmount(Double value) {
        this.depositAmount = value;
    }

    /**
     * Gets the value of the depositDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDepositDate() {
        return depositDate;
    }

    /**
     * Sets the value of the depositDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDepositDate(XMLGregorianCalendar value) {
        this.depositDate = value;
    }

}
