//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 04:20:56 PM PST 
//


package com.kcdataservices.affiliate.itinerary;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.kcdataservices.affiliate.common.AgencyType;
import com.kcdataservices.affiliate.common.BooleanFlagType;


/**
 * Represents the itinerary header type
 * 
 * <p>Java class for ItineraryHeaderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItineraryHeaderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bookingStatus">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="OPT"/>
 *               &lt;enumeration value="GTD"/>
 *               &lt;enumeration value="PIF"/>
 *               &lt;enumeration value="DRD"/>
 *               &lt;enumeration value="CANC"/>
 *               &lt;enumeration value="DEP"/>
 *               &lt;enumeration value="EXP"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="bookingDate" type="{http://affiliate.kcdataservices.com/common}DateType"/>
 *         &lt;element name="travelDate" type="{http://affiliate.kcdataservices.com/common}DateType"/>
 *         &lt;element name="agency" type="{http://affiliate.kcdataservices.com/common}AgencyType"/>
 *         &lt;element name="tourPrice" type="{http://affiliate.kcdataservices.com/common}AmountType"/>
 *         &lt;element name="amountDue" type="{http://affiliate.kcdataservices.com/common}AmountType"/>
 *         &lt;element name="minimumAmount" type="{http://affiliate.kcdataservices.com/common}AmountType"/>
 *         &lt;element name="commission" type="{http://affiliate.kcdataservices.com/common}AmountType"/>
 *         &lt;element name="promoSavings" type="{http://affiliate.kcdataservices.com/common}AmountType"/>
 *         &lt;element name="optionDate" type="{http://affiliate.kcdataservices.com/common}DateType" minOccurs="0"/>
 *         &lt;element name="cancellationDate" type="{http://affiliate.kcdataservices.com/common}DateType" minOccurs="0"/>
 *         &lt;element name="ticketingDate" type="{http://affiliate.kcdataservices.com/common}DateType" minOccurs="0"/>
 *         &lt;element name="guaranteedDate" type="{http://affiliate.kcdataservices.com/common}DateType" minOccurs="0"/>
 *         &lt;element name="finalDueDate" type="{http://affiliate.kcdataservices.com/common}DateType" minOccurs="0"/>
 *         &lt;element name="applyPaymentAllowed" type="{http://affiliate.kcdataservices.com/common}BooleanFlagType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItineraryHeaderType", propOrder = {
    "bookingStatus",
    "bookingDate",
    "travelDate",
    "agency",
    "tourPrice",
    "amountDue",
    "minimumAmount",
    "commission",
    "promoSavings",
    "optionDate",
    "cancellationDate",
    "ticketingDate",
    "guaranteedDate",
    "finalDueDate",
    "applyPaymentAllowed"
})
public class ItineraryHeaderType {

    @XmlElement(required = true)
    protected String bookingStatus;
    @XmlElement(required = true)
    protected XMLGregorianCalendar bookingDate;
    @XmlElement(required = true)
    protected XMLGregorianCalendar travelDate;
    @XmlElement(required = true)
    protected AgencyType agency;
    protected double tourPrice;
    protected double amountDue;
    protected double minimumAmount;
    protected double commission;
    protected double promoSavings;
    protected XMLGregorianCalendar optionDate;
    protected XMLGregorianCalendar cancellationDate;
    protected XMLGregorianCalendar ticketingDate;
    protected XMLGregorianCalendar guaranteedDate;
    protected XMLGregorianCalendar finalDueDate;
    protected BooleanFlagType applyPaymentAllowed;

    /**
     * Gets the value of the bookingStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookingStatus() {
        return bookingStatus;
    }

    /**
     * Sets the value of the bookingStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookingStatus(String value) {
        this.bookingStatus = value;
    }

    /**
     * Gets the value of the bookingDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBookingDate() {
        return bookingDate;
    }

    /**
     * Sets the value of the bookingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBookingDate(XMLGregorianCalendar value) {
        this.bookingDate = value;
    }

    /**
     * Gets the value of the travelDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTravelDate() {
        return travelDate;
    }

    /**
     * Sets the value of the travelDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTravelDate(XMLGregorianCalendar value) {
        this.travelDate = value;
    }

    /**
     * Gets the value of the agency property.
     * 
     * @return
     *     possible object is
     *     {@link AgencyType }
     *     
     */
    public AgencyType getAgency() {
        return agency;
    }

    /**
     * Sets the value of the agency property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgencyType }
     *     
     */
    public void setAgency(AgencyType value) {
        this.agency = value;
    }

    /**
     * Gets the value of the tourPrice property.
     * 
     */
    public double getTourPrice() {
        return tourPrice;
    }

    /**
     * Sets the value of the tourPrice property.
     * 
     */
    public void setTourPrice(double value) {
        this.tourPrice = value;
    }

    /**
     * Gets the value of the amountDue property.
     * 
     */
    public double getAmountDue() {
        return amountDue;
    }

    /**
     * Sets the value of the amountDue property.
     * 
     */
    public void setAmountDue(double value) {
        this.amountDue = value;
    }

    /**
     * Gets the value of the minimumAmount property.
     * 
     */
    public double getMinimumAmount() {
        return minimumAmount;
    }

    /**
     * Sets the value of the minimumAmount property.
     * 
     */
    public void setMinimumAmount(double value) {
        this.minimumAmount = value;
    }

    /**
     * Gets the value of the commission property.
     * 
     */
    public double getCommission() {
        return commission;
    }

    /**
     * Sets the value of the commission property.
     * 
     */
    public void setCommission(double value) {
        this.commission = value;
    }

    /**
     * Gets the value of the promoSavings property.
     * 
     */
    public double getPromoSavings() {
        return promoSavings;
    }

    /**
     * Sets the value of the promoSavings property.
     * 
     */
    public void setPromoSavings(double value) {
        this.promoSavings = value;
    }

    /**
     * Gets the value of the optionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOptionDate() {
        return optionDate;
    }

    /**
     * Sets the value of the optionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOptionDate(XMLGregorianCalendar value) {
        this.optionDate = value;
    }

    /**
     * Gets the value of the cancellationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCancellationDate() {
        return cancellationDate;
    }

    /**
     * Sets the value of the cancellationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCancellationDate(XMLGregorianCalendar value) {
        this.cancellationDate = value;
    }

    /**
     * Gets the value of the ticketingDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTicketingDate() {
        return ticketingDate;
    }

    /**
     * Sets the value of the ticketingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTicketingDate(XMLGregorianCalendar value) {
        this.ticketingDate = value;
    }

    /**
     * Gets the value of the guaranteedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGuaranteedDate() {
        return guaranteedDate;
    }

    /**
     * Sets the value of the guaranteedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setGuaranteedDate(XMLGregorianCalendar value) {
        this.guaranteedDate = value;
    }

    /**
     * Gets the value of the finalDueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFinalDueDate() {
        return finalDueDate;
    }

    /**
     * Sets the value of the finalDueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFinalDueDate(XMLGregorianCalendar value) {
        this.finalDueDate = value;
    }

    /**
     * Gets the value of the applyPaymentAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanFlagType }
     *     
     */
    public BooleanFlagType getApplyPaymentAllowed() {
        return applyPaymentAllowed;
    }

    /**
     * Sets the value of the applyPaymentAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanFlagType }
     *     
     */
    public void setApplyPaymentAllowed(BooleanFlagType value) {
        this.applyPaymentAllowed = value;
    }

}
