//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 04:20:56 PM PST 
//


package com.kcdataservices.affiliate.itinerary;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import com.kcdataservices.affiliate.common.AddressType;
import com.kcdataservices.affiliate.common.PaymentInformationType;
import com.kcdataservices.affiliate.common.PromotionType;
import com.kcdataservices.affiliate.flights.SelectedFlightType;
import com.kcdataservices.affiliate.hotels.SelectedHotelType;
import com.kcdataservices.affiliate.insurance.SelectedInsuranceType;
import com.kcdataservices.affiliate.packages.SelectedMultiDestinationPackageType;
import com.kcdataservices.affiliate.packages.SelectedPackageType;
import com.kcdataservices.affiliate.services.SelectedServiceType;
import com.kcdataservices.affiliate.vehicles.SelectedVehicleType;


/**
 * Represents the complete Itinerary
 * 
 * <p>Java class for ItineraryRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItineraryRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="promotions" type="{http://affiliate.kcdataservices.com/common}PromotionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="flight" type="{http://affiliate.kcdataservices.com/flights}SelectedFlightType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="hotel" type="{http://affiliate.kcdataservices.com/hotels}SelectedHotelType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="vehicle" type="{http://affiliate.kcdataservices.com/vehicles}SelectedVehicleType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="selectedPackage" type="{http://affiliate.kcdataservices.com/packages}SelectedPackageType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="multiDestPackage" type="{http://affiliate.kcdataservices.com/packages}SelectedMultiDestinationPackageType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="service" type="{http://affiliate.kcdataservices.com/services}SelectedServiceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="insurance" type="{http://affiliate.kcdataservices.com/insurance}SelectedInsuranceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="guest" type="{http://affiliate.kcdataservices.com/itinerary}GuestInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="paymentInformation" type="{http://affiliate.kcdataservices.com/common}PaymentInformationType" minOccurs="0"/>
 *         &lt;element name="shippingAddress" type="{http://affiliate.kcdataservices.com/common}AddressType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItineraryRequestType", propOrder = {
    "promotions",
    "flight",
    "hotel",
    "vehicle",
    "selectedPackage",
    "multiDestPackage",
    "service",
    "insurance",
    "guest",
    "paymentInformation",
    "shippingAddress"
})
@XmlSeeAlso({
    ItineraryResponseType.class
})
public class ItineraryRequestType {

    protected List<PromotionType> promotions;
    protected List<SelectedFlightType> flight;
    protected List<SelectedHotelType> hotel;
    protected List<SelectedVehicleType> vehicle;
    protected List<SelectedPackageType> selectedPackage;
    protected List<SelectedMultiDestinationPackageType> multiDestPackage;
    protected List<SelectedServiceType> service;
    protected List<SelectedInsuranceType> insurance;
    protected List<GuestInfoType> guest;
    protected PaymentInformationType paymentInformation;
    protected AddressType shippingAddress;

    /**
     * Gets the value of the promotions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the promotions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPromotions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PromotionType }
     * 
     * 
     */
    public List<PromotionType> getPromotions() {
        if (promotions == null) {
            promotions = new ArrayList<PromotionType>();
        }
        return this.promotions;
    }

    /**
     * Gets the value of the flight property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the flight property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFlight().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SelectedFlightType }
     * 
     * 
     */
    public List<SelectedFlightType> getFlight() {
        if (flight == null) {
            flight = new ArrayList<SelectedFlightType>();
        }
        return this.flight;
    }

    /**
     * Gets the value of the hotel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hotel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHotel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SelectedHotelType }
     * 
     * 
     */
    public List<SelectedHotelType> getHotel() {
        if (hotel == null) {
            hotel = new ArrayList<SelectedHotelType>();
        }
        return this.hotel;
    }

    /**
     * Gets the value of the vehicle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vehicle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVehicle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SelectedVehicleType }
     * 
     * 
     */
    public List<SelectedVehicleType> getVehicle() {
        if (vehicle == null) {
            vehicle = new ArrayList<SelectedVehicleType>();
        }
        return this.vehicle;
    }

    /**
     * Gets the value of the selectedPackage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the selectedPackage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSelectedPackage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SelectedPackageType }
     * 
     * 
     */
    public List<SelectedPackageType> getSelectedPackage() {
        if (selectedPackage == null) {
            selectedPackage = new ArrayList<SelectedPackageType>();
        }
        return this.selectedPackage;
    }

    /**
     * Gets the value of the multiDestPackage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the multiDestPackage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMultiDestPackage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SelectedMultiDestinationPackageType }
     * 
     * 
     */
    public List<SelectedMultiDestinationPackageType> getMultiDestPackage() {
        if (multiDestPackage == null) {
            multiDestPackage = new ArrayList<SelectedMultiDestinationPackageType>();
        }
        return this.multiDestPackage;
    }

    /**
     * Gets the value of the service property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the service property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SelectedServiceType }
     * 
     * 
     */
    public List<SelectedServiceType> getService() {
        if (service == null) {
            service = new ArrayList<SelectedServiceType>();
        }
        return this.service;
    }

    /**
     * Gets the value of the insurance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the insurance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInsurance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SelectedInsuranceType }
     * 
     * 
     */
    public List<SelectedInsuranceType> getInsurance() {
        if (insurance == null) {
            insurance = new ArrayList<SelectedInsuranceType>();
        }
        return this.insurance;
    }

    /**
     * Gets the value of the guest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the guest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGuest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GuestInfoType }
     * 
     * 
     */
    public List<GuestInfoType> getGuest() {
        if (guest == null) {
            guest = new ArrayList<GuestInfoType>();
        }
        return this.guest;
    }

    /**
     * Gets the value of the paymentInformation property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentInformationType }
     *     
     */
    public PaymentInformationType getPaymentInformation() {
        return paymentInformation;
    }

    /**
     * Sets the value of the paymentInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentInformationType }
     *     
     */
    public void setPaymentInformation(PaymentInformationType value) {
        this.paymentInformation = value;
    }

    /**
     * Gets the value of the shippingAddress property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getShippingAddress() {
        return shippingAddress;
    }

    /**
     * Sets the value of the shippingAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setShippingAddress(AddressType value) {
        this.shippingAddress = value;
    }

}
