//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 04:20:56 PM PST 
//


package com.kcdataservices.affiliate.itinerary;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import com.kcdataservices.affiliate.common.PaymentHistoryType;


/**
 * Represents the Itinerary response type
 * 
 * <p>Java class for ItineraryResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItineraryResponseType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://affiliate.kcdataservices.com/itinerary}ItineraryRequestType">
 *       &lt;sequence>
 *         &lt;element name="confirmatioNumber" type="{http://affiliate.kcdataservices.com/common}ConfirmationNumberType" minOccurs="0"/>
 *         &lt;element name="header" type="{http://affiliate.kcdataservices.com/itinerary}ItineraryHeaderType" minOccurs="0"/>
 *         &lt;element name="price" type="{http://affiliate.kcdataservices.com/itinerary}ItineraryPriceType" minOccurs="0"/>
 *         &lt;element name="charge" type="{http://affiliate.kcdataservices.com/itinerary}ItineraryChargesType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="notice" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="paymentHistory" type="{http://affiliate.kcdataservices.com/common}PaymentHistoryType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItineraryResponseType", propOrder = {
    "confirmatioNumber",
    "header",
    "price",
    "charge",
    "notice",
    "paymentHistory"
})
public class ItineraryResponseType
    extends ItineraryRequestType
{

    protected String confirmatioNumber;
    protected ItineraryHeaderType header;
    protected ItineraryPriceType price;
    protected List<ItineraryChargesType> charge;
    protected List<String> notice;
    protected List<PaymentHistoryType> paymentHistory;

    /**
     * Gets the value of the confirmatioNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfirmatioNumber() {
        return confirmatioNumber;
    }

    /**
     * Sets the value of the confirmatioNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfirmatioNumber(String value) {
        this.confirmatioNumber = value;
    }

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link ItineraryHeaderType }
     *     
     */
    public ItineraryHeaderType getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItineraryHeaderType }
     *     
     */
    public void setHeader(ItineraryHeaderType value) {
        this.header = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link ItineraryPriceType }
     *     
     */
    public ItineraryPriceType getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItineraryPriceType }
     *     
     */
    public void setPrice(ItineraryPriceType value) {
        this.price = value;
    }

    /**
     * Gets the value of the charge property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the charge property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCharge().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItineraryChargesType }
     * 
     * 
     */
    public List<ItineraryChargesType> getCharge() {
        if (charge == null) {
            charge = new ArrayList<ItineraryChargesType>();
        }
        return this.charge;
    }

    /**
     * Gets the value of the notice property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the notice property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNotice().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNotice() {
        if (notice == null) {
            notice = new ArrayList<String>();
        }
        return this.notice;
    }

    /**
     * Gets the value of the paymentHistory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paymentHistory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaymentHistory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PaymentHistoryType }
     * 
     * 
     */
    public List<PaymentHistoryType> getPaymentHistory() {
        if (paymentHistory == null) {
            paymentHistory = new ArrayList<PaymentHistoryType>();
        }
        return this.paymentHistory;
    }

}
