//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 04:20:56 PM PST 
//


package com.kcdataservices.affiliate.itinerary;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.kcdataservices.affiliate.itinerary package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.kcdataservices.affiliate.itinerary
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ItineraryResponseType }
     * 
     */
    public ItineraryResponseType createItineraryResponseType() {
        return new ItineraryResponseType();
    }

    /**
     * Create an instance of {@link ItineraryChargesType }
     * 
     */
    public ItineraryChargesType createItineraryChargesType() {
        return new ItineraryChargesType();
    }

    /**
     * Create an instance of {@link ItineraryRequestType }
     * 
     */
    public ItineraryRequestType createItineraryRequestType() {
        return new ItineraryRequestType();
    }

    /**
     * Create an instance of {@link GuestPriceBreakupType }
     * 
     */
    public GuestPriceBreakupType createGuestPriceBreakupType() {
        return new GuestPriceBreakupType();
    }

    /**
     * Create an instance of {@link GuestInfoType }
     * 
     */
    public GuestInfoType createGuestInfoType() {
        return new GuestInfoType();
    }

    /**
     * Create an instance of {@link ItineraryPriceType }
     * 
     */
    public ItineraryPriceType createItineraryPriceType() {
        return new ItineraryPriceType();
    }

    /**
     * Create an instance of {@link ItineraryHeaderType }
     * 
     */
    public ItineraryHeaderType createItineraryHeaderType() {
        return new ItineraryHeaderType();
    }

    /**
     * Create an instance of {@link PassportInfoType }
     * 
     */
    public PassportInfoType createPassportInfoType() {
        return new PassportInfoType();
    }

    /**
     * Create an instance of {@link CancellationRulesType }
     * 
     */
    public CancellationRulesType createCancellationRulesType() {
        return new CancellationRulesType();
    }

}
