//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 05:31:18 PM PST 
//


package com.kcdataservices.affiliate.vehicles;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.kcdataservices.affiliate.vehicles package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.kcdataservices.affiliate.vehicles
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VehicleAvailabilityType }
     * 
     */
    public VehicleAvailabilityType createVehicleAvailabilityType() {
        return new VehicleAvailabilityType();
    }

    /**
     * Create an instance of {@link SelectedVehicleType }
     * 
     */
    public SelectedVehicleType createSelectedVehicleType() {
        return new SelectedVehicleType();
    }

    /**
     * Create an instance of {@link VehicleOptionType }
     * 
     */
    public VehicleOptionType createVehicleOptionType() {
        return new VehicleOptionType();
    }

}
