//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 05:31:18 PM PST 
//


package com.kcdataservices.affiliate.commonresponse;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import com.kcdataservices.affiliate.availabilityresponse.ItineraryAvailabilityResponse;
import com.kcdataservices.affiliate.common.ApplicationInfoType;
import com.kcdataservices.affiliate.common.BooleanFlagType;
import com.kcdataservices.affiliate.common.ErrorType;


/**
 * Response schema extended all the response objects
 * 
 * <p>Java class for CommonResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommonResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="applicationInfo" type="{http://affiliate.kcdataservices.com/common}ApplicationInfoType" minOccurs="0"/>
 *         &lt;element name="successful" type="{http://affiliate.kcdataservices.com/common}BooleanFlagType"/>
 *         &lt;element name="errors" type="{http://affiliate.kcdataservices.com/common}ErrorType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="warnings" type="{http://affiliate.kcdataservices.com/common}ErrorType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="messages" type="{http://affiliate.kcdataservices.com/common}ErrorType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommonResponseType", propOrder = {
    "applicationInfo",
    "successful",
    "errors",
    "warnings",
    "messages"
})
@XmlSeeAlso({
    ItineraryAvailabilityResponse.class
})
public class CommonResponseType {

    protected ApplicationInfoType applicationInfo;
    @XmlElement(required = true)
    protected BooleanFlagType successful;
    protected List<ErrorType> errors;
    protected List<ErrorType> warnings;
    protected List<ErrorType> messages;

    /**
     * Gets the value of the applicationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationInfoType }
     *     
     */
    public ApplicationInfoType getApplicationInfo() {
        return applicationInfo;
    }

    /**
     * Sets the value of the applicationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationInfoType }
     *     
     */
    public void setApplicationInfo(ApplicationInfoType value) {
        this.applicationInfo = value;
    }

    /**
     * Gets the value of the successful property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanFlagType }
     *     
     */
    public BooleanFlagType getSuccessful() {
        return successful;
    }

    /**
     * Sets the value of the successful property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanFlagType }
     *     
     */
    public void setSuccessful(BooleanFlagType value) {
        this.successful = value;
    }

    /**
     * Gets the value of the errors property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the errors property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getErrors().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ErrorType }
     * 
     * 
     */
    public List<ErrorType> getErrors() {
        if (errors == null) {
            errors = new ArrayList<ErrorType>();
        }
        return this.errors;
    }

    /**
     * Gets the value of the warnings property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the warnings property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWarnings().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ErrorType }
     * 
     * 
     */
    public List<ErrorType> getWarnings() {
        if (warnings == null) {
            warnings = new ArrayList<ErrorType>();
        }
        return this.warnings;
    }

    /**
     * Gets the value of the messages property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the messages property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessages().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ErrorType }
     * 
     * 
     */
    public List<ErrorType> getMessages() {
        if (messages == null) {
            messages = new ArrayList<ErrorType>();
        }
        return this.messages;
    }

}
