//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 04:19:50 PM PST 
//


package com.kcdataservices.affiliate.bookpricerequest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.kcdataservices.affiliate.common.BooleanFlagType;
import com.kcdataservices.affiliate.commonrequest.CommonRequestType;
import com.kcdataservices.affiliate.itinerary.ItineraryRequestType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://affiliate.kcdataservices.com/commonrequest}CommonRequestType">
 *       &lt;sequence>
 *         &lt;element name="createReservation" type="{http://affiliate.kcdataservices.com/common}BooleanFlagType"/>
 *         &lt;element name="itinerary" type="{http://affiliate.kcdataservices.com/itinerary}ItineraryRequestType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "createReservation",
    "itinerary"
})
@XmlRootElement(name = "BookPriceItineraryRequest")
public class BookPriceItineraryRequest
    extends CommonRequestType
{

    @XmlElement(required = true, defaultValue = "N")
    protected BooleanFlagType createReservation;
    @XmlElement(required = true)
    protected ItineraryRequestType itinerary;

    /**
     * Gets the value of the createReservation property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanFlagType }
     *     
     */
    public BooleanFlagType getCreateReservation() {
        return createReservation;
    }

    /**
     * Sets the value of the createReservation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanFlagType }
     *     
     */
    public void setCreateReservation(BooleanFlagType value) {
        this.createReservation = value;
    }

    /**
     * Gets the value of the itinerary property.
     * 
     * @return
     *     possible object is
     *     {@link ItineraryRequestType }
     *     
     */
    public ItineraryRequestType getItinerary() {
        return itinerary;
    }

    /**
     * Sets the value of the itinerary property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItineraryRequestType }
     *     
     */
    public void setItinerary(ItineraryRequestType value) {
        this.itinerary = value;
    }

}
